//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// <copyright file="LStB201601.cs" company="DATALINE GmbH &amp; Co. KG">
// Copyright (c) DATALINE GmbH &amp; Co. KG. All rights reserved.
// </copyright>

using System.Collections.Generic;

namespace Dataline.Elster.Lohn.LStB201601
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "lstb_LohnsteuerbescheinigungCType", Namespace = "http://www.elsterlohn.de/2016-01/XMLSchema")]
    [System.Xml.Serialization.XmlRootAttribute("Lohnsteuerbescheinigung", Namespace = "http://www.elsterlohn.de/2016-01/XMLSchema", IsNullable = false)]
    public partial class lstb_LohnsteuerbescheinigungCType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private lstb_LohnsteuerbescheinigungCTypeAnweisung anweisungField;

        private lstb_LohnsteuerbescheinigungCTypeDauer dauerField;

        private lstb_AllgemeinCType allgemeinField;

        private List<lstb_BesteuerungsmerkmaleCTypeELStAM> besteuerungsmerkmaleField;

        private lstb_BesteuerungsgrundlagenCType besteuerungsgrundlagenField;

        private lstb_LohnsteuerbescheinigungVersionSType versionField;

        private lstb_LohnsteuerbescheinigungCTypeArt artField;

        /// <remarks/>
        public lstb_LohnsteuerbescheinigungCTypeAnweisung Anweisung
        {
            get
            {
                return this.anweisungField;
            }
            set
            {
                this.anweisungField = value;
                this.RaisePropertyChanged("Anweisung");
            }
        }

        /// <remarks/>
        public lstb_LohnsteuerbescheinigungCTypeDauer Dauer
        {
            get
            {
                return this.dauerField;
            }
            set
            {
                this.dauerField = value;
                this.RaisePropertyChanged("Dauer");
            }
        }

        /// <remarks/>
        public lstb_AllgemeinCType Allgemein
        {
            get
            {
                return this.allgemeinField;
            }
            set
            {
                this.allgemeinField = value;
                this.RaisePropertyChanged("Allgemein");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ELStAM", IsNullable = false)]
        public List<lstb_BesteuerungsmerkmaleCTypeELStAM> Besteuerungsmerkmale
        {
            get
            {
                return this.besteuerungsmerkmaleField;
            }
            set
            {
                this.besteuerungsmerkmaleField = value;
                this.RaisePropertyChanged("Besteuerungsmerkmale");
            }
        }

        /// <remarks/>
        public lstb_BesteuerungsgrundlagenCType Besteuerungsgrundlagen
        {
            get
            {
                return this.besteuerungsgrundlagenField;
            }
            set
            {
                this.besteuerungsgrundlagenField = value;
                this.RaisePropertyChanged("Besteuerungsgrundlagen");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute]
        public lstb_LohnsteuerbescheinigungVersionSType version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute]
        public lstb_LohnsteuerbescheinigungCTypeArt art
        {
            get
            {
                return this.artField;
            }
            set
            {
                this.artField = value;
                this.RaisePropertyChanged("art");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.elsterlohn.de/2016-01/XMLSchema")]
    public partial class lstb_LohnsteuerbescheinigungCTypeAnweisung : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string kmIdField;

        private string refKmIdField;

        private lstb_LohnsteuerbescheinigungCTypeAnweisungArt artField;

        /// <remarks/>
        public string KmId
        {
            get
            {
                return this.kmIdField;
            }
            set
            {
                this.kmIdField = value;
                this.RaisePropertyChanged("KmId");
            }
        }

        /// <remarks/>
        public string RefKmId
        {
            get
            {
                return this.refKmIdField;
            }
            set
            {
                this.refKmIdField = value;
                this.RaisePropertyChanged("RefKmId");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute]
        public lstb_LohnsteuerbescheinigungCTypeAnweisungArt art
        {
            get
            {
                return this.artField;
            }
            set
            {
                this.artField = value;
                this.RaisePropertyChanged("art");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.elsterlohn.de/2016-01/XMLSchema")]
    public enum lstb_LohnsteuerbescheinigungCTypeAnweisungArt
    {

        /// <remarks/>
        Neu,

        /// <remarks/>
        Korrektur,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.elsterlohn.de/2016-01/XMLSchema")]
    public partial class lstb_LohnsteuerbescheinigungCTypeDauer : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string anfangField;

        private string endeField;

        private lstb_LohnsteuerbescheinigungJahrSType jahrField;

        /// <remarks/>
        public string Anfang
        {
            get
            {
                return this.anfangField;
            }
            set
            {
                this.anfangField = value;
                this.RaisePropertyChanged("Anfang");
            }
        }

        /// <remarks/>
        public string Ende
        {
            get
            {
                return this.endeField;
            }
            set
            {
                this.endeField = value;
                this.RaisePropertyChanged("Ende");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute]
        public lstb_LohnsteuerbescheinigungJahrSType jahr
        {
            get
            {
                return this.jahrField;
            }
            set
            {
                this.jahrField = value;
                this.RaisePropertyChanged("jahr");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "lstb_LohnsteuerbescheinigungJahrSType", Namespace = "http://www.elsterlohn.de/2016-01/XMLSchema")]
    public enum lstb_LohnsteuerbescheinigungJahrSType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2016")]
        Item2016,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "lstb_AllgemeinCType", Namespace = "http://www.elsterlohn.de/2016-01/XMLSchema")]
    public partial class lstb_AllgemeinCType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string eTINField;

        private string idNrField;

        private string ordnungsmerkmalField;

        private lstb_PersonCType personField;

        /// <remarks/>
        public string ETIN
        {
            get
            {
                return this.eTINField;
            }
            set
            {
                this.eTINField = value;
                this.RaisePropertyChanged("ETIN");
            }
        }

        /// <remarks/>
        public string IdNr
        {
            get
            {
                return this.idNrField;
            }
            set
            {
                this.idNrField = value;
                this.RaisePropertyChanged("IdNr");
            }
        }

        /// <remarks/>
        public string Ordnungsmerkmal
        {
            get
            {
                return this.ordnungsmerkmalField;
            }
            set
            {
                this.ordnungsmerkmalField = value;
                this.RaisePropertyChanged("Ordnungsmerkmal");
            }
        }

        /// <remarks/>
        public lstb_PersonCType Person
        {
            get
            {
                return this.personField;
            }
            set
            {
                this.personField = value;
                this.RaisePropertyChanged("Person");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "lstb_PersonCType", Namespace = "http://www.elsterlohn.de/2016-01/XMLSchema")]
    public partial class lstb_PersonCType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private lstb_PersonCTypeFamilienname familiennameField;

        private lstb_PersonCTypeGeburtsname geburtsnameField;

        private string geburtsdatumField;

        private lstb_AdresseCType adresseField;

        private lstb_PersonCTypeGeschlecht geschlechtField;

        /// <remarks/>
        public lstb_PersonCTypeFamilienname Familienname
        {
            get
            {
                return this.familiennameField;
            }
            set
            {
                this.familiennameField = value;
                this.RaisePropertyChanged("Familienname");
            }
        }

        /// <remarks/>
        public lstb_PersonCTypeGeburtsname Geburtsname
        {
            get
            {
                return this.geburtsnameField;
            }
            set
            {
                this.geburtsnameField = value;
                this.RaisePropertyChanged("Geburtsname");
            }
        }

        /// <remarks/>
        public string Geburtsdatum
        {
            get
            {
                return this.geburtsdatumField;
            }
            set
            {
                this.geburtsdatumField = value;
                this.RaisePropertyChanged("Geburtsdatum");
            }
        }

        /// <remarks/>
        public lstb_AdresseCType Adresse
        {
            get
            {
                return this.adresseField;
            }
            set
            {
                this.adresseField = value;
                this.RaisePropertyChanged("Adresse");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute]
        public lstb_PersonCTypeGeschlecht geschlecht
        {
            get
            {
                return this.geschlechtField;
            }
            set
            {
                this.geschlechtField = value;
                this.RaisePropertyChanged("geschlecht");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.elsterlohn.de/2016-01/XMLSchema")]
    public partial class lstb_PersonCTypeFamilienname : object, System.ComponentModel.INotifyPropertyChanged
    {

        private object[] itemsField;

        private ItemsChoiceType[] itemsElementNameField;

        private string namensvorsatzField;

        private string namenszusatzField;

        private string titelField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Blockname", typeof(allg_BlocknameCType))]
        [System.Xml.Serialization.XmlElementAttribute("Name", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Vorname", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public ItemsChoiceType[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
                this.RaisePropertyChanged("ItemsElementName");
            }
        }

        /// <remarks/>
        public string Namensvorsatz
        {
            get
            {
                return this.namensvorsatzField;
            }
            set
            {
                this.namensvorsatzField = value;
                this.RaisePropertyChanged("Namensvorsatz");
            }
        }

        /// <remarks/>
        public string Namenszusatz
        {
            get
            {
                return this.namenszusatzField;
            }
            set
            {
                this.namenszusatzField = value;
                this.RaisePropertyChanged("Namenszusatz");
            }
        }

        /// <remarks/>
        public string Titel
        {
            get
            {
                return this.titelField;
            }
            set
            {
                this.titelField = value;
                this.RaisePropertyChanged("Titel");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.elsterlohn.de/2016-01/XMLSchema", IncludeInSchema = false)]
    public enum ItemsChoiceType
    {

        /// <remarks/>
        Blockname,

        /// <remarks/>
        Name,

        /// <remarks/>
        Vorname,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.elsterlohn.de/2016-01/XMLSchema")]
    public partial class lstb_PersonCTypeGeburtsname : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string nameField;

        private string namensvorsatzField;

        private string namenszusatzField;

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }

        /// <remarks/>
        public string Namensvorsatz
        {
            get
            {
                return this.namensvorsatzField;
            }
            set
            {
                this.namensvorsatzField = value;
                this.RaisePropertyChanged("Namensvorsatz");
            }
        }

        /// <remarks/>
        public string Namenszusatz
        {
            get
            {
                return this.namenszusatzField;
            }
            set
            {
                this.namenszusatzField = value;
                this.RaisePropertyChanged("Namenszusatz");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "lstb_AdresseCType", Namespace = "http://www.elsterlohn.de/2016-01/XMLSchema")]
    public partial class lstb_AdresseCType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string strField;

        private string hausnummerField;

        private string hNrZusatzField;

        private string anschriftenzusatzField;

        private string ortField;

        private object itemField;

        private string postfachOrtField;

        private string postfachField;

        private string postfachPLZField;

        /// <remarks/>
        public string Str
        {
            get
            {
                return this.strField;
            }
            set
            {
                this.strField = value;
                this.RaisePropertyChanged("Str");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string Hausnummer
        {
            get
            {
                return this.hausnummerField;
            }
            set
            {
                this.hausnummerField = value;
                this.RaisePropertyChanged("Hausnummer");
            }
        }

        /// <remarks/>
        public string HNrZusatz
        {
            get
            {
                return this.hNrZusatzField;
            }
            set
            {
                this.hNrZusatzField = value;
                this.RaisePropertyChanged("HNrZusatz");
            }
        }

        /// <remarks/>
        public string Anschriftenzusatz
        {
            get
            {
                return this.anschriftenzusatzField;
            }
            set
            {
                this.anschriftenzusatzField = value;
                this.RaisePropertyChanged("Anschriftenzusatz");
            }
        }

        /// <remarks/>
        public string Ort
        {
            get
            {
                return this.ortField;
            }
            set
            {
                this.ortField = value;
                this.RaisePropertyChanged("Ort");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AuslandsPLZ", typeof(AuslandsPLZCType))]
        [System.Xml.Serialization.XmlElementAttribute("PLZ", typeof(string))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }

        /// <remarks/>
        public string PostfachOrt
        {
            get
            {
                return this.postfachOrtField;
            }
            set
            {
                this.postfachOrtField = value;
                this.RaisePropertyChanged("PostfachOrt");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "positiveInteger")]
        public string Postfach
        {
            get
            {
                return this.postfachField;
            }
            set
            {
                this.postfachField = value;
                this.RaisePropertyChanged("Postfach");
            }
        }

        /// <remarks/>
        public string PostfachPLZ
        {
            get
            {
                return this.postfachPLZField;
            }
            set
            {
                this.postfachPLZField = value;
                this.RaisePropertyChanged("PostfachPLZ");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "AuslandsPLZCType", Namespace = "http://www.elsterlohn.de/2016-01/XMLSchema")]
    public partial class AuslandsPLZCType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string laenderkennzeichenField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute]
        public string laenderkennzeichen
        {
            get
            {
                return this.laenderkennzeichenField;
            }
            set
            {
                this.laenderkennzeichenField = value;
                this.RaisePropertyChanged("laenderkennzeichen");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.elsterlohn.de/2016-01/XMLSchema")]
    public enum lstb_PersonCTypeGeschlecht
    {

        /// <remarks/>
        M,

        /// <remarks/>
        W,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.elsterlohn.de/2016-01/XMLSchema")]
    public partial class lstb_BesteuerungsmerkmaleCTypeELStAM : object, System.ComponentModel.INotifyPropertyChanged
    {

        private lstb_BesteuerungsmerkmaleCTypeELStAMSteuerklasse steuerklasseField;

        private lstb_BesteuerungsmerkmaleCTypeELStAMKinder kinderField;

        private lstb_BesteuerungsmerkmaleCTypeELStAMKirchensteuerabzug kirchensteuerabzugField;

        private lstb_BesteuerungsmerkmaleCTypeELStAMSteuerfreibetrag steuerfreibetragField;

        private lstb_BesteuerungsmerkmaleCTypeELStAMHinzurechnungsbetrag hinzurechnungsbetragField;

        private System.DateTime gueltig_abField;

        /// <remarks/>
        public lstb_BesteuerungsmerkmaleCTypeELStAMSteuerklasse Steuerklasse
        {
            get
            {
                return this.steuerklasseField;
            }
            set
            {
                this.steuerklasseField = value;
                this.RaisePropertyChanged("Steuerklasse");
            }
        }

        /// <remarks/>
        public lstb_BesteuerungsmerkmaleCTypeELStAMKinder Kinder
        {
            get
            {
                return this.kinderField;
            }
            set
            {
                this.kinderField = value;
                this.RaisePropertyChanged("Kinder");
            }
        }

        /// <remarks/>
        public lstb_BesteuerungsmerkmaleCTypeELStAMKirchensteuerabzug Kirchensteuerabzug
        {
            get
            {
                return this.kirchensteuerabzugField;
            }
            set
            {
                this.kirchensteuerabzugField = value;
                this.RaisePropertyChanged("Kirchensteuerabzug");
            }
        }

        /// <remarks/>
        public lstb_BesteuerungsmerkmaleCTypeELStAMSteuerfreibetrag Steuerfreibetrag
        {
            get
            {
                return this.steuerfreibetragField;
            }
            set
            {
                this.steuerfreibetragField = value;
                this.RaisePropertyChanged("Steuerfreibetrag");
            }
        }

        /// <remarks/>
        public lstb_BesteuerungsmerkmaleCTypeELStAMHinzurechnungsbetrag Hinzurechnungsbetrag
        {
            get
            {
                return this.hinzurechnungsbetragField;
            }
            set
            {
                this.hinzurechnungsbetragField = value;
                this.RaisePropertyChanged("Hinzurechnungsbetrag");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime gueltig_ab
        {
            get
            {
                return this.gueltig_abField;
            }
            set
            {
                this.gueltig_abField = value;
                this.RaisePropertyChanged("gueltig_ab");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.elsterlohn.de/2016-01/XMLSchema")]
    public partial class lstb_BesteuerungsmerkmaleCTypeELStAMSteuerklasse : object, System.ComponentModel.INotifyPropertyChanged
    {

        private decimal faktorField;

        private bool faktorFieldSpecified;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute]
        public decimal faktor
        {
            get
            {
                return this.faktorField;
            }
            set
            {
                this.faktorField = value;
                this.RaisePropertyChanged("faktor");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public bool faktorSpecified
        {
            get
            {
                return this.faktorFieldSpecified;
            }
            set
            {
                this.faktorFieldSpecified = value;
                this.RaisePropertyChanged("faktorSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType = "integer")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.elsterlohn.de/2016-01/XMLSchema")]
    public partial class lstb_BesteuerungsmerkmaleCTypeELStAMKinder : object, System.ComponentModel.INotifyPropertyChanged
    {

        private decimal valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute]
        public decimal Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.elsterlohn.de/2016-01/XMLSchema")]
    public partial class lstb_BesteuerungsmerkmaleCTypeELStAMKirchensteuerabzug : object, System.ComponentModel.INotifyPropertyChanged
    {

        private allg_Konfession_ab2008SType konfessionField;

        private allg_Konfession_ab2008SType ehegkonfessionField;

        private bool ehegkonfessionFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute]
        public allg_Konfession_ab2008SType konfession
        {
            get
            {
                return this.konfessionField;
            }
            set
            {
                this.konfessionField = value;
                this.RaisePropertyChanged("konfession");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute]
        public allg_Konfession_ab2008SType ehegkonfession
        {
            get
            {
                return this.ehegkonfessionField;
            }
            set
            {
                this.ehegkonfessionField = value;
                this.RaisePropertyChanged("ehegkonfession");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public bool ehegkonfessionSpecified
        {
            get
            {
                return this.ehegkonfessionFieldSpecified;
            }
            set
            {
                this.ehegkonfessionFieldSpecified = value;
                this.RaisePropertyChanged("ehegkonfessionSpecified");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.elsterlohn.de/2016-01/XMLSchema")]
    public partial class lstb_BesteuerungsmerkmaleCTypeELStAMSteuerfreibetrag : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string jahrField;

        private string monatField;

        private decimal wocheField;

        private bool wocheFieldSpecified;

        private decimal tagField;

        private bool tagFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")]
        public string jahr
        {
            get
            {
                return this.jahrField;
            }
            set
            {
                this.jahrField = value;
                this.RaisePropertyChanged("jahr");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")]
        public string monat
        {
            get
            {
                return this.monatField;
            }
            set
            {
                this.monatField = value;
                this.RaisePropertyChanged("monat");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute]
        public decimal woche
        {
            get
            {
                return this.wocheField;
            }
            set
            {
                this.wocheField = value;
                this.RaisePropertyChanged("woche");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public bool wocheSpecified
        {
            get
            {
                return this.wocheFieldSpecified;
            }
            set
            {
                this.wocheFieldSpecified = value;
                this.RaisePropertyChanged("wocheSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute]
        public decimal tag
        {
            get
            {
                return this.tagField;
            }
            set
            {
                this.tagField = value;
                this.RaisePropertyChanged("tag");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public bool tagSpecified
        {
            get
            {
                return this.tagFieldSpecified;
            }
            set
            {
                this.tagFieldSpecified = value;
                this.RaisePropertyChanged("tagSpecified");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.elsterlohn.de/2016-01/XMLSchema")]
    public partial class lstb_BesteuerungsmerkmaleCTypeELStAMHinzurechnungsbetrag : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string jahrField;

        private string monatField;

        private decimal wocheField;

        private bool wocheFieldSpecified;

        private decimal tagField;

        private bool tagFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")]
        public string jahr
        {
            get
            {
                return this.jahrField;
            }
            set
            {
                this.jahrField = value;
                this.RaisePropertyChanged("jahr");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")]
        public string monat
        {
            get
            {
                return this.monatField;
            }
            set
            {
                this.monatField = value;
                this.RaisePropertyChanged("monat");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute]
        public decimal woche
        {
            get
            {
                return this.wocheField;
            }
            set
            {
                this.wocheField = value;
                this.RaisePropertyChanged("woche");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public bool wocheSpecified
        {
            get
            {
                return this.wocheFieldSpecified;
            }
            set
            {
                this.wocheFieldSpecified = value;
                this.RaisePropertyChanged("wocheSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute]
        public decimal tag
        {
            get
            {
                return this.tagField;
            }
            set
            {
                this.tagField = value;
                this.RaisePropertyChanged("tag");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public bool tagSpecified
        {
            get
            {
                return this.tagFieldSpecified;
            }
            set
            {
                this.tagFieldSpecified = value;
                this.RaisePropertyChanged("tagSpecified");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "lstb_BesteuerungsgrundlagenCType", Namespace = "http://www.elsterlohn.de/2016-01/XMLSchema")]
    public partial class lstb_BesteuerungsgrundlagenCType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string anzahlUField;

        private decimal bruttoArbLohnField;

        private decimal lSteuerField;

        private decimal soliField;

        private decimal arbnKiSteuerField;

        private bool arbnKiSteuerFieldSpecified;

        private decimal ehegKiSteuerField;

        private bool ehegKiSteuerFieldSpecified;

        private List<lstb_BesteuerungsgrundlagenCTypeVBez> vBezField;

        private List<lstb_BesteuerungsgrundlagenCTypeErmStVBezMKalJahr> ermStVBezMKalJahrField;

        private decimal ermStBetrMKalJahrField;

        private bool ermStBetrMKalJahrFieldSpecified;

        private decimal lSteuerMKalJahrField;

        private decimal soliMKalJahrField;

        private decimal kiSteuerArbnMKalJahrField;

        private bool kiSteuerArbnMKalJahrFieldSpecified;

        private decimal kiSteuerEhegMKalJahrField;

        private bool kiSteuerEhegMKalJahrFieldSpecified;

        private decimal kurzArbGeldField;

        private bool kurzArbGeldFieldSpecified;

        private decimal stFreiArbLohnDBAField;

        private bool stFreiArbLohnDBAFieldSpecified;

        private decimal stFreiArbLohnATEField;

        private bool stFreiArbLohnATEFieldSpecified;

        private decimal stFreiArbgLeistgField;

        private bool stFreiArbgLeistgFieldSpecified;

        private decimal pauschArbgLeistgField;

        private bool pauschArbgLeistgFieldSpecified;

        private decimal stPflichtArbLohnMKalJahrField;

        private bool stPflichtArbLohnMKalJahrFieldSpecified;

        private decimal stFreiVerpflegField;

        private bool stFreiVerpflegFieldSpecified;

        private decimal stFreiDopHaushaltField;

        private bool stFreiDopHaushaltFieldSpecified;

        private decimal arbgAnteilRenVersField;

        private bool arbgAnteilRenVersFieldSpecified;

        private decimal arbgAnteilBerufsVersField;

        private bool arbgAnteilBerufsVersFieldSpecified;

        private decimal arbnAnteilRenVersField;

        private bool arbnAnteilRenVersFieldSpecified;

        private decimal arbnAnteilBerufsVersField;

        private bool arbnAnteilBerufsVersFieldSpecified;

        private decimal stFreiGeKrankVersField;

        private bool stFreiGeKrankVersFieldSpecified;

        private decimal stFreiPrKrankVersField;

        private bool stFreiPrKrankVersFieldSpecified;

        private decimal stFreiGePflegeVersField;

        private bool stFreiGePflegeVersFieldSpecified;

        private decimal arbnAnteilKrankVersField;

        private bool arbnAnteilKrankVersFieldSpecified;

        private decimal arbnAnteilPflegVersField;

        private bool arbnAnteilPflegVersFieldSpecified;

        private decimal arbnAnteilArblVersField;

        private bool arbnAnteilArblVersFieldSpecified;

        private decimal beitrPrKrankVersField;

        private bool beitrPrKrankVersFieldSpecified;

        private decimal ausgezKinderGeldField;

        private bool ausgezKinderGeldFieldSpecified;

        private decimal freibetragDbaTuerkeiField;

        private bool freibetragDbaTuerkeiFieldSpecified;

        private string grossbuchstabenField;

        private List<lstb_BesteuerungsgrundlagenCTypeKammerbeitrag> kammerbeitragField;

        private decimal arbnAnteilWBUmlageField;

        private bool arbnAnteilWBUmlageFieldSpecified;

        private decimal arbgAnteilZusatzVersField;

        private bool arbgAnteilZusatzVersFieldSpecified;

        private decimal arbnAnteilZusatzVersField;

        private bool arbnAnteilZusatzVersFieldSpecified;

        private int anzahlArbTagField;

        private bool anzahlArbTagFieldSpecified;

        private decimal stFreiFahrtKAuswField;

        private bool stFreiFahrtKAuswFieldSpecified;

        private List<lstb_BesteuerungsgrundlagenCTypeNErmStVBezMKalJahr> nErmStVBezMKalJahrField;

        private decimal stFreiArbgZuschBerufsVersField;

        private bool stFreiArbgZuschBerufsVersFieldSpecified;

        private List<lstb_BesteuerungsgrundlagenCTypeWert> wertField;

        private List<lstb_BesteuerungsgrundlagenCTypeText> textField;

        private lstb_ArbeitgeberCType arbeitgeberField;

        /// <remarks/>
        public string AnzahlU
        {
            get
            {
                return this.anzahlUField;
            }
            set
            {
                this.anzahlUField = value;
                this.RaisePropertyChanged("AnzahlU");
            }
        }

        /// <remarks/>
        public decimal BruttoArbLohn
        {
            get
            {
                return this.bruttoArbLohnField;
            }
            set
            {
                this.bruttoArbLohnField = value;
                this.RaisePropertyChanged("BruttoArbLohn");
            }
        }

        /// <remarks/>
        public decimal LSteuer
        {
            get
            {
                return this.lSteuerField;
            }
            set
            {
                this.lSteuerField = value;
                this.RaisePropertyChanged("LSteuer");
            }
        }

        /// <remarks/>
        public decimal Soli
        {
            get
            {
                return this.soliField;
            }
            set
            {
                this.soliField = value;
                this.RaisePropertyChanged("Soli");
            }
        }

        /// <remarks/>
        public decimal ArbnKiSteuer
        {
            get
            {
                return this.arbnKiSteuerField;
            }
            set
            {
                this.arbnKiSteuerField = value;
                this.RaisePropertyChanged("ArbnKiSteuer");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public bool ArbnKiSteuerSpecified
        {
            get
            {
                return this.arbnKiSteuerFieldSpecified;
            }
            set
            {
                this.arbnKiSteuerFieldSpecified = value;
                this.RaisePropertyChanged("ArbnKiSteuerSpecified");
            }
        }

        /// <remarks/>
        public decimal EhegKiSteuer
        {
            get
            {
                return this.ehegKiSteuerField;
            }
            set
            {
                this.ehegKiSteuerField = value;
                this.RaisePropertyChanged("EhegKiSteuer");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public bool EhegKiSteuerSpecified
        {
            get
            {
                return this.ehegKiSteuerFieldSpecified;
            }
            set
            {
                this.ehegKiSteuerFieldSpecified = value;
                this.RaisePropertyChanged("EhegKiSteuerSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VBez")]
        public List<lstb_BesteuerungsgrundlagenCTypeVBez> VBez
        {
            get
            {
                return this.vBezField;
            }
            set
            {
                this.vBezField = value;
                this.RaisePropertyChanged("VBez");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ErmStVBezMKalJahr")]
        public List<lstb_BesteuerungsgrundlagenCTypeErmStVBezMKalJahr> ErmStVBezMKalJahr
        {
            get
            {
                return this.ermStVBezMKalJahrField;
            }
            set
            {
                this.ermStVBezMKalJahrField = value;
                this.RaisePropertyChanged("ErmStVBezMKalJahr");
            }
        }

        /// <remarks/>
        public decimal ErmStBetrMKalJahr
        {
            get
            {
                return this.ermStBetrMKalJahrField;
            }
            set
            {
                this.ermStBetrMKalJahrField = value;
                this.RaisePropertyChanged("ErmStBetrMKalJahr");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public bool ErmStBetrMKalJahrSpecified
        {
            get
            {
                return this.ermStBetrMKalJahrFieldSpecified;
            }
            set
            {
                this.ermStBetrMKalJahrFieldSpecified = value;
                this.RaisePropertyChanged("ErmStBetrMKalJahrSpecified");
            }
        }

        /// <remarks/>
        public decimal LSteuerMKalJahr
        {
            get
            {
                return this.lSteuerMKalJahrField;
            }
            set
            {
                this.lSteuerMKalJahrField = value;
                this.RaisePropertyChanged("LSteuerMKalJahr");
            }
        }

        /// <remarks/>
        public decimal SoliMKalJahr
        {
            get
            {
                return this.soliMKalJahrField;
            }
            set
            {
                this.soliMKalJahrField = value;
                this.RaisePropertyChanged("SoliMKalJahr");
            }
        }

        /// <remarks/>
        public decimal KiSteuerArbnMKalJahr
        {
            get
            {
                return this.kiSteuerArbnMKalJahrField;
            }
            set
            {
                this.kiSteuerArbnMKalJahrField = value;
                this.RaisePropertyChanged("KiSteuerArbnMKalJahr");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public bool KiSteuerArbnMKalJahrSpecified
        {
            get
            {
                return this.kiSteuerArbnMKalJahrFieldSpecified;
            }
            set
            {
                this.kiSteuerArbnMKalJahrFieldSpecified = value;
                this.RaisePropertyChanged("KiSteuerArbnMKalJahrSpecified");
            }
        }

        /// <remarks/>
        public decimal KiSteuerEhegMKalJahr
        {
            get
            {
                return this.kiSteuerEhegMKalJahrField;
            }
            set
            {
                this.kiSteuerEhegMKalJahrField = value;
                this.RaisePropertyChanged("KiSteuerEhegMKalJahr");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public bool KiSteuerEhegMKalJahrSpecified
        {
            get
            {
                return this.kiSteuerEhegMKalJahrFieldSpecified;
            }
            set
            {
                this.kiSteuerEhegMKalJahrFieldSpecified = value;
                this.RaisePropertyChanged("KiSteuerEhegMKalJahrSpecified");
            }
        }

        /// <remarks/>
        public decimal KurzArbGeld
        {
            get
            {
                return this.kurzArbGeldField;
            }
            set
            {
                this.kurzArbGeldField = value;
                this.RaisePropertyChanged("KurzArbGeld");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public bool KurzArbGeldSpecified
        {
            get
            {
                return this.kurzArbGeldFieldSpecified;
            }
            set
            {
                this.kurzArbGeldFieldSpecified = value;
                this.RaisePropertyChanged("KurzArbGeldSpecified");
            }
        }

        /// <remarks/>
        public decimal StFreiArbLohnDBA
        {
            get
            {
                return this.stFreiArbLohnDBAField;
            }
            set
            {
                this.stFreiArbLohnDBAField = value;
                this.RaisePropertyChanged("StFreiArbLohnDBA");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public bool StFreiArbLohnDBASpecified
        {
            get
            {
                return this.stFreiArbLohnDBAFieldSpecified;
            }
            set
            {
                this.stFreiArbLohnDBAFieldSpecified = value;
                this.RaisePropertyChanged("StFreiArbLohnDBASpecified");
            }
        }

        /// <remarks/>
        public decimal StFreiArbLohnATE
        {
            get
            {
                return this.stFreiArbLohnATEField;
            }
            set
            {
                this.stFreiArbLohnATEField = value;
                this.RaisePropertyChanged("StFreiArbLohnATE");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public bool StFreiArbLohnATESpecified
        {
            get
            {
                return this.stFreiArbLohnATEFieldSpecified;
            }
            set
            {
                this.stFreiArbLohnATEFieldSpecified = value;
                this.RaisePropertyChanged("StFreiArbLohnATESpecified");
            }
        }

        /// <remarks/>
        public decimal StFreiArbgLeistg
        {
            get
            {
                return this.stFreiArbgLeistgField;
            }
            set
            {
                this.stFreiArbgLeistgField = value;
                this.RaisePropertyChanged("StFreiArbgLeistg");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public bool StFreiArbgLeistgSpecified
        {
            get
            {
                return this.stFreiArbgLeistgFieldSpecified;
            }
            set
            {
                this.stFreiArbgLeistgFieldSpecified = value;
                this.RaisePropertyChanged("StFreiArbgLeistgSpecified");
            }
        }

        /// <remarks/>
        public decimal PauschArbgLeistg
        {
            get
            {
                return this.pauschArbgLeistgField;
            }
            set
            {
                this.pauschArbgLeistgField = value;
                this.RaisePropertyChanged("PauschArbgLeistg");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public bool PauschArbgLeistgSpecified
        {
            get
            {
                return this.pauschArbgLeistgFieldSpecified;
            }
            set
            {
                this.pauschArbgLeistgFieldSpecified = value;
                this.RaisePropertyChanged("PauschArbgLeistgSpecified");
            }
        }

        /// <remarks/>
        public decimal StPflichtArbLohnMKalJahr
        {
            get
            {
                return this.stPflichtArbLohnMKalJahrField;
            }
            set
            {
                this.stPflichtArbLohnMKalJahrField = value;
                this.RaisePropertyChanged("StPflichtArbLohnMKalJahr");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public bool StPflichtArbLohnMKalJahrSpecified
        {
            get
            {
                return this.stPflichtArbLohnMKalJahrFieldSpecified;
            }
            set
            {
                this.stPflichtArbLohnMKalJahrFieldSpecified = value;
                this.RaisePropertyChanged("StPflichtArbLohnMKalJahrSpecified");
            }
        }

        /// <remarks/>
        public decimal StFreiVerpfleg
        {
            get
            {
                return this.stFreiVerpflegField;
            }
            set
            {
                this.stFreiVerpflegField = value;
                this.RaisePropertyChanged("StFreiVerpfleg");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public bool StFreiVerpflegSpecified
        {
            get
            {
                return this.stFreiVerpflegFieldSpecified;
            }
            set
            {
                this.stFreiVerpflegFieldSpecified = value;
                this.RaisePropertyChanged("StFreiVerpflegSpecified");
            }
        }

        /// <remarks/>
        public decimal StFreiDopHaushalt
        {
            get
            {
                return this.stFreiDopHaushaltField;
            }
            set
            {
                this.stFreiDopHaushaltField = value;
                this.RaisePropertyChanged("StFreiDopHaushalt");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public bool StFreiDopHaushaltSpecified
        {
            get
            {
                return this.stFreiDopHaushaltFieldSpecified;
            }
            set
            {
                this.stFreiDopHaushaltFieldSpecified = value;
                this.RaisePropertyChanged("StFreiDopHaushaltSpecified");
            }
        }

        /// <remarks/>
        public decimal ArbgAnteilRenVers
        {
            get
            {
                return this.arbgAnteilRenVersField;
            }
            set
            {
                this.arbgAnteilRenVersField = value;
                this.RaisePropertyChanged("ArbgAnteilRenVers");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public bool ArbgAnteilRenVersSpecified
        {
            get
            {
                return this.arbgAnteilRenVersFieldSpecified;
            }
            set
            {
                this.arbgAnteilRenVersFieldSpecified = value;
                this.RaisePropertyChanged("ArbgAnteilRenVersSpecified");
            }
        }

        /// <remarks/>
        public decimal ArbgAnteilBerufsVers
        {
            get
            {
                return this.arbgAnteilBerufsVersField;
            }
            set
            {
                this.arbgAnteilBerufsVersField = value;
                this.RaisePropertyChanged("ArbgAnteilBerufsVers");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public bool ArbgAnteilBerufsVersSpecified
        {
            get
            {
                return this.arbgAnteilBerufsVersFieldSpecified;
            }
            set
            {
                this.arbgAnteilBerufsVersFieldSpecified = value;
                this.RaisePropertyChanged("ArbgAnteilBerufsVersSpecified");
            }
        }

        /// <remarks/>
        public decimal ArbnAnteilRenVers
        {
            get
            {
                return this.arbnAnteilRenVersField;
            }
            set
            {
                this.arbnAnteilRenVersField = value;
                this.RaisePropertyChanged("ArbnAnteilRenVers");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public bool ArbnAnteilRenVersSpecified
        {
            get
            {
                return this.arbnAnteilRenVersFieldSpecified;
            }
            set
            {
                this.arbnAnteilRenVersFieldSpecified = value;
                this.RaisePropertyChanged("ArbnAnteilRenVersSpecified");
            }
        }

        /// <remarks/>
        public decimal ArbnAnteilBerufsVers
        {
            get
            {
                return this.arbnAnteilBerufsVersField;
            }
            set
            {
                this.arbnAnteilBerufsVersField = value;
                this.RaisePropertyChanged("ArbnAnteilBerufsVers");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public bool ArbnAnteilBerufsVersSpecified
        {
            get
            {
                return this.arbnAnteilBerufsVersFieldSpecified;
            }
            set
            {
                this.arbnAnteilBerufsVersFieldSpecified = value;
                this.RaisePropertyChanged("ArbnAnteilBerufsVersSpecified");
            }
        }

        /// <remarks/>
        public decimal StFreiGeKrankVers
        {
            get
            {
                return this.stFreiGeKrankVersField;
            }
            set
            {
                this.stFreiGeKrankVersField = value;
                this.RaisePropertyChanged("StFreiGeKrankVers");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public bool StFreiGeKrankVersSpecified
        {
            get
            {
                return this.stFreiGeKrankVersFieldSpecified;
            }
            set
            {
                this.stFreiGeKrankVersFieldSpecified = value;
                this.RaisePropertyChanged("StFreiGeKrankVersSpecified");
            }
        }

        /// <remarks/>
        public decimal StFreiPrKrankVers
        {
            get
            {
                return this.stFreiPrKrankVersField;
            }
            set
            {
                this.stFreiPrKrankVersField = value;
                this.RaisePropertyChanged("StFreiPrKrankVers");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public bool StFreiPrKrankVersSpecified
        {
            get
            {
                return this.stFreiPrKrankVersFieldSpecified;
            }
            set
            {
                this.stFreiPrKrankVersFieldSpecified = value;
                this.RaisePropertyChanged("StFreiPrKrankVersSpecified");
            }
        }

        /// <remarks/>
        public decimal StFreiGePflegeVers
        {
            get
            {
                return this.stFreiGePflegeVersField;
            }
            set
            {
                this.stFreiGePflegeVersField = value;
                this.RaisePropertyChanged("StFreiGePflegeVers");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public bool StFreiGePflegeVersSpecified
        {
            get
            {
                return this.stFreiGePflegeVersFieldSpecified;
            }
            set
            {
                this.stFreiGePflegeVersFieldSpecified = value;
                this.RaisePropertyChanged("StFreiGePflegeVersSpecified");
            }
        }

        /// <remarks/>
        public decimal ArbnAnteilKrankVers
        {
            get
            {
                return this.arbnAnteilKrankVersField;
            }
            set
            {
                this.arbnAnteilKrankVersField = value;
                this.RaisePropertyChanged("ArbnAnteilKrankVers");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public bool ArbnAnteilKrankVersSpecified
        {
            get
            {
                return this.arbnAnteilKrankVersFieldSpecified;
            }
            set
            {
                this.arbnAnteilKrankVersFieldSpecified = value;
                this.RaisePropertyChanged("ArbnAnteilKrankVersSpecified");
            }
        }

        /// <remarks/>
        public decimal ArbnAnteilPflegVers
        {
            get
            {
                return this.arbnAnteilPflegVersField;
            }
            set
            {
                this.arbnAnteilPflegVersField = value;
                this.RaisePropertyChanged("ArbnAnteilPflegVers");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public bool ArbnAnteilPflegVersSpecified
        {
            get
            {
                return this.arbnAnteilPflegVersFieldSpecified;
            }
            set
            {
                this.arbnAnteilPflegVersFieldSpecified = value;
                this.RaisePropertyChanged("ArbnAnteilPflegVersSpecified");
            }
        }

        /// <remarks/>
        public decimal ArbnAnteilArblVers
        {
            get
            {
                return this.arbnAnteilArblVersField;
            }
            set
            {
                this.arbnAnteilArblVersField = value;
                this.RaisePropertyChanged("ArbnAnteilArblVers");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public bool ArbnAnteilArblVersSpecified
        {
            get
            {
                return this.arbnAnteilArblVersFieldSpecified;
            }
            set
            {
                this.arbnAnteilArblVersFieldSpecified = value;
                this.RaisePropertyChanged("ArbnAnteilArblVersSpecified");
            }
        }

        /// <remarks/>
        public decimal BeitrPrKrankVers
        {
            get
            {
                return this.beitrPrKrankVersField;
            }
            set
            {
                this.beitrPrKrankVersField = value;
                this.RaisePropertyChanged("BeitrPrKrankVers");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public bool BeitrPrKrankVersSpecified
        {
            get
            {
                return this.beitrPrKrankVersFieldSpecified;
            }
            set
            {
                this.beitrPrKrankVersFieldSpecified = value;
                this.RaisePropertyChanged("BeitrPrKrankVersSpecified");
            }
        }

        /// <remarks/>
        public decimal AusgezKinderGeld
        {
            get
            {
                return this.ausgezKinderGeldField;
            }
            set
            {
                this.ausgezKinderGeldField = value;
                this.RaisePropertyChanged("AusgezKinderGeld");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public bool AusgezKinderGeldSpecified
        {
            get
            {
                return this.ausgezKinderGeldFieldSpecified;
            }
            set
            {
                this.ausgezKinderGeldFieldSpecified = value;
                this.RaisePropertyChanged("AusgezKinderGeldSpecified");
            }
        }

        /// <remarks/>
        public decimal FreibetragDbaTuerkei
        {
            get
            {
                return this.freibetragDbaTuerkeiField;
            }
            set
            {
                this.freibetragDbaTuerkeiField = value;
                this.RaisePropertyChanged("FreibetragDbaTuerkei");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public bool FreibetragDbaTuerkeiSpecified
        {
            get
            {
                return this.freibetragDbaTuerkeiFieldSpecified;
            }
            set
            {
                this.freibetragDbaTuerkeiFieldSpecified = value;
                this.RaisePropertyChanged("FreibetragDbaTuerkeiSpecified");
            }
        }

        /// <remarks/>
        public string Grossbuchstaben
        {
            get
            {
                return this.grossbuchstabenField;
            }
            set
            {
                this.grossbuchstabenField = value;
                this.RaisePropertyChanged("Grossbuchstaben");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Kammerbeitrag")]
        public List<lstb_BesteuerungsgrundlagenCTypeKammerbeitrag> Kammerbeitrag
        {
            get
            {
                return this.kammerbeitragField;
            }
            set
            {
                this.kammerbeitragField = value;
                this.RaisePropertyChanged("Kammerbeitrag");
            }
        }

        /// <remarks/>
        public decimal ArbnAnteilWBUmlage
        {
            get
            {
                return this.arbnAnteilWBUmlageField;
            }
            set
            {
                this.arbnAnteilWBUmlageField = value;
                this.RaisePropertyChanged("ArbnAnteilWBUmlage");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public bool ArbnAnteilWBUmlageSpecified
        {
            get
            {
                return this.arbnAnteilWBUmlageFieldSpecified;
            }
            set
            {
                this.arbnAnteilWBUmlageFieldSpecified = value;
                this.RaisePropertyChanged("ArbnAnteilWBUmlageSpecified");
            }
        }

        /// <remarks/>
        public decimal ArbgAnteilZusatzVers
        {
            get
            {
                return this.arbgAnteilZusatzVersField;
            }
            set
            {
                this.arbgAnteilZusatzVersField = value;
                this.RaisePropertyChanged("ArbgAnteilZusatzVers");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public bool ArbgAnteilZusatzVersSpecified
        {
            get
            {
                return this.arbgAnteilZusatzVersFieldSpecified;
            }
            set
            {
                this.arbgAnteilZusatzVersFieldSpecified = value;
                this.RaisePropertyChanged("ArbgAnteilZusatzVersSpecified");
            }
        }

        /// <remarks/>
        public decimal ArbnAnteilZusatzVers
        {
            get
            {
                return this.arbnAnteilZusatzVersField;
            }
            set
            {
                this.arbnAnteilZusatzVersField = value;
                this.RaisePropertyChanged("ArbnAnteilZusatzVers");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public bool ArbnAnteilZusatzVersSpecified
        {
            get
            {
                return this.arbnAnteilZusatzVersFieldSpecified;
            }
            set
            {
                this.arbnAnteilZusatzVersFieldSpecified = value;
                this.RaisePropertyChanged("ArbnAnteilZusatzVersSpecified");
            }
        }

        /// <remarks/>
        public int AnzahlArbTag
        {
            get
            {
                return this.anzahlArbTagField;
            }
            set
            {
                this.anzahlArbTagField = value;
                this.RaisePropertyChanged("AnzahlArbTag");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public bool AnzahlArbTagSpecified
        {
            get
            {
                return this.anzahlArbTagFieldSpecified;
            }
            set
            {
                this.anzahlArbTagFieldSpecified = value;
                this.RaisePropertyChanged("AnzahlArbTagSpecified");
            }
        }

        /// <remarks/>
        public decimal StFreiFahrtKAusw
        {
            get
            {
                return this.stFreiFahrtKAuswField;
            }
            set
            {
                this.stFreiFahrtKAuswField = value;
                this.RaisePropertyChanged("StFreiFahrtKAusw");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public bool StFreiFahrtKAuswSpecified
        {
            get
            {
                return this.stFreiFahrtKAuswFieldSpecified;
            }
            set
            {
                this.stFreiFahrtKAuswFieldSpecified = value;
                this.RaisePropertyChanged("StFreiFahrtKAuswSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NErmStVBezMKalJahr")]
        public List<lstb_BesteuerungsgrundlagenCTypeNErmStVBezMKalJahr> NErmStVBezMKalJahr
        {
            get
            {
                return this.nErmStVBezMKalJahrField;
            }
            set
            {
                this.nErmStVBezMKalJahrField = value;
                this.RaisePropertyChanged("NErmStVBezMKalJahr");
            }
        }

        /// <remarks/>
        public decimal StFreiArbgZuschBerufsVers
        {
            get
            {
                return this.stFreiArbgZuschBerufsVersField;
            }
            set
            {
                this.stFreiArbgZuschBerufsVersField = value;
                this.RaisePropertyChanged("StFreiArbgZuschBerufsVers");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public bool StFreiArbgZuschBerufsVersSpecified
        {
            get
            {
                return this.stFreiArbgZuschBerufsVersFieldSpecified;
            }
            set
            {
                this.stFreiArbgZuschBerufsVersFieldSpecified = value;
                this.RaisePropertyChanged("StFreiArbgZuschBerufsVersSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Wert")]
        public List<lstb_BesteuerungsgrundlagenCTypeWert> Wert
        {
            get
            {
                return this.wertField;
            }
            set
            {
                this.wertField = value;
                this.RaisePropertyChanged("Wert");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Text")]
        public List<lstb_BesteuerungsgrundlagenCTypeText> Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }

        /// <remarks/>
        public lstb_ArbeitgeberCType Arbeitgeber
        {
            get
            {
                return this.arbeitgeberField;
            }
            set
            {
                this.arbeitgeberField = value;
                this.RaisePropertyChanged("Arbeitgeber");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.elsterlohn.de/2016-01/XMLSchema")]
    public partial class lstb_BesteuerungsgrundlagenCTypeVBez : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string jahrField;

        private allg_Datum_MMSType beginnField;

        private bool beginnFieldSpecified;

        private allg_Datum_MMSType endeField;

        private bool endeFieldSpecified;

        private decimal bmgfreibetragField;

        private decimal einmversbezugField;

        private bool einmversbezugFieldSpecified;

        private decimal valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "gYear")]
        public string jahr
        {
            get
            {
                return this.jahrField;
            }
            set
            {
                this.jahrField = value;
                this.RaisePropertyChanged("jahr");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute]
        public allg_Datum_MMSType beginn
        {
            get
            {
                return this.beginnField;
            }
            set
            {
                this.beginnField = value;
                this.RaisePropertyChanged("beginn");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public bool beginnSpecified
        {
            get
            {
                return this.beginnFieldSpecified;
            }
            set
            {
                this.beginnFieldSpecified = value;
                this.RaisePropertyChanged("beginnSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute]
        public allg_Datum_MMSType ende
        {
            get
            {
                return this.endeField;
            }
            set
            {
                this.endeField = value;
                this.RaisePropertyChanged("ende");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public bool endeSpecified
        {
            get
            {
                return this.endeFieldSpecified;
            }
            set
            {
                this.endeFieldSpecified = value;
                this.RaisePropertyChanged("endeSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute]
        public decimal bmgfreibetrag
        {
            get
            {
                return this.bmgfreibetragField;
            }
            set
            {
                this.bmgfreibetragField = value;
                this.RaisePropertyChanged("bmgfreibetrag");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute]
        public decimal einmversbezug
        {
            get
            {
                return this.einmversbezugField;
            }
            set
            {
                this.einmversbezugField = value;
                this.RaisePropertyChanged("einmversbezug");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public bool einmversbezugSpecified
        {
            get
            {
                return this.einmversbezugFieldSpecified;
            }
            set
            {
                this.einmversbezugFieldSpecified = value;
                this.RaisePropertyChanged("einmversbezugSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute]
        public decimal Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.elsterlohn.de/2016-01/XMLSchema")]
    public partial class lstb_BesteuerungsgrundlagenCTypeErmStVBezMKalJahr : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string jahrField;

        private decimal valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "gYear")]
        public string jahr
        {
            get
            {
                return this.jahrField;
            }
            set
            {
                this.jahrField = value;
                this.RaisePropertyChanged("jahr");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute]
        public decimal Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.elsterlohn.de/2016-01/XMLSchema")]
    public partial class lstb_BesteuerungsgrundlagenCTypeKammerbeitrag : object, System.ComponentModel.INotifyPropertyChanged
    {

        private lstb_BesteuerungsgrundlagenCTypeKammerbeitragBundesland bundeslandField;

        private decimal valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute]
        public lstb_BesteuerungsgrundlagenCTypeKammerbeitragBundesland bundesland
        {
            get
            {
                return this.bundeslandField;
            }
            set
            {
                this.bundeslandField = value;
                this.RaisePropertyChanged("bundesland");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute]
        public decimal Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.elsterlohn.de/2016-01/XMLSchema")]
    public enum lstb_BesteuerungsgrundlagenCTypeKammerbeitragBundesland
    {

        /// <remarks/>
        HB,

        /// <remarks/>
        SL,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.elsterlohn.de/2016-01/XMLSchema")]
    public partial class lstb_BesteuerungsgrundlagenCTypeNErmStVBezMKalJahr : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string jahrField;

        private decimal valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "gYear")]
        public string jahr
        {
            get
            {
                return this.jahrField;
            }
            set
            {
                this.jahrField = value;
                this.RaisePropertyChanged("jahr");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute]
        public decimal Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.elsterlohn.de/2016-01/XMLSchema")]
    public partial class lstb_BesteuerungsgrundlagenCTypeWert : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string nameField;

        private decimal valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute]
        public decimal Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.elsterlohn.de/2016-01/XMLSchema")]
    public partial class lstb_BesteuerungsgrundlagenCTypeText : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string nameField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "lstb_ArbeitgeberCType", Namespace = "http://www.elsterlohn.de/2016-01/XMLSchema")]
    public partial class lstb_ArbeitgeberCType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string arbGNameField;

        private string arbGFANrField;

        private string arbGFANameField;

        private string arbGStNrField;

        private lstb_ArbGAdresseCType adresseField;

        /// <remarks/>
        public string ArbGName
        {
            get
            {
                return this.arbGNameField;
            }
            set
            {
                this.arbGNameField = value;
                this.RaisePropertyChanged("ArbGName");
            }
        }

        /// <remarks/>
        public string ArbGFANr
        {
            get
            {
                return this.arbGFANrField;
            }
            set
            {
                this.arbGFANrField = value;
                this.RaisePropertyChanged("ArbGFANr");
            }
        }

        /// <remarks/>
        public string ArbGFAName
        {
            get
            {
                return this.arbGFANameField;
            }
            set
            {
                this.arbGFANameField = value;
                this.RaisePropertyChanged("ArbGFAName");
            }
        }

        /// <remarks/>
        public string ArbGStNr
        {
            get
            {
                return this.arbGStNrField;
            }
            set
            {
                this.arbGStNrField = value;
                this.RaisePropertyChanged("ArbGStNr");
            }
        }

        /// <remarks/>
        public lstb_ArbGAdresseCType Adresse
        {
            get
            {
                return this.adresseField;
            }
            set
            {
                this.adresseField = value;
                this.RaisePropertyChanged("Adresse");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "lstb_ArbGAdresseCType", Namespace = "http://www.elsterlohn.de/2016-01/XMLSchema")]
    public partial class lstb_ArbGAdresseCType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private object[] itemsField;

        private ItemsChoiceType2[] itemsElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Anschriftenzusatz", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("AuslandsPLZ", typeof(AuslandsPLZCType))]
        [System.Xml.Serialization.XmlElementAttribute("GKPLZ", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("HNrZusatz", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Hausnummer", typeof(string), DataType = "integer")]
        [System.Xml.Serialization.XmlElementAttribute("Ort", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("PLZ", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Postfach", typeof(string), DataType = "positiveInteger")]
        [System.Xml.Serialization.XmlElementAttribute("PostfachOrt", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("PostfachPLZ", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Str", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute]
        public ItemsChoiceType2[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
                this.RaisePropertyChanged("ItemsElementName");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.elsterlohn.de/2016-01/XMLSchema", IncludeInSchema = false)]
    public enum ItemsChoiceType2
    {

        /// <remarks/>
        Anschriftenzusatz,

        /// <remarks/>
        AuslandsPLZ,

        /// <remarks/>
        GKPLZ,

        /// <remarks/>
        HNrZusatz,

        /// <remarks/>
        Hausnummer,

        /// <remarks/>
        Ort,

        /// <remarks/>
        PLZ,

        /// <remarks/>
        Postfach,

        /// <remarks/>
        PostfachOrt,

        /// <remarks/>
        PostfachPLZ,

        /// <remarks/>
        Str,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "lstb_LohnsteuerbescheinigungVersionSType", Namespace = "http://www.elsterlohn.de/2016-01/XMLSchema")]
    public enum lstb_LohnsteuerbescheinigungVersionSType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("201601")]
        Item201601,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.elsterlohn.de/2016-01/XMLSchema")]
    public enum lstb_LohnsteuerbescheinigungCTypeArt
    {

        /// <remarks/>
        ELStAM,
    }
}
