//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.6.81.0.
// 

using Dataline.Elster.Basis;

namespace Dataline.Elster.Anmeldung.Umsatzsteuer200121 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.elster.de/2002/XMLSchema")]
    public partial class NutzdatenCType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private usta_AnmeldungssteuernCType anmeldungssteuernField;
        
        /// <remarks/>
        public usta_AnmeldungssteuernCType Anmeldungssteuern {
            get {
                return this.anmeldungssteuernField;
            }
            set {
                this.anmeldungssteuernField = value;
                this.RaisePropertyChanged("Anmeldungssteuern");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.elster.de/2002/XMLSchema")]
    public partial class usta_AnmeldungssteuernCType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private usta_DatenlieferantCType datenLieferantField;
        
        private string erstellungsdatumField;
        
        private usta_SteuerfallCType steuerfallField;
        
        private usta_AnmeldungssteuernCTypeVersion versionField;
        
        private string artField;
        
        /// <remarks/>
        public usta_DatenlieferantCType DatenLieferant {
            get {
                return this.datenLieferantField;
            }
            set {
                this.datenLieferantField = value;
                this.RaisePropertyChanged("DatenLieferant");
            }
        }
        
        /// <remarks/>
        public string Erstellungsdatum {
            get {
                return this.erstellungsdatumField;
            }
            set {
                this.erstellungsdatumField = value;
                this.RaisePropertyChanged("Erstellungsdatum");
            }
        }
        
        /// <remarks/>
        public usta_SteuerfallCType Steuerfall {
            get {
                return this.steuerfallField;
            }
            set {
                this.steuerfallField = value;
                this.RaisePropertyChanged("Steuerfall");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public usta_AnmeldungssteuernCTypeVersion version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string art {
            get {
                return this.artField;
            }
            set {
                this.artField = value;
                this.RaisePropertyChanged("art");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.elster.de/2002/XMLSchema")]
    public partial class usta_DatenlieferantCType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string strasseField;
        
        private string pLZField;
        
        private string ortField;
        
        private string telefonField;
        
        private string emailField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        public string Strasse {
            get {
                return this.strasseField;
            }
            set {
                this.strasseField = value;
                this.RaisePropertyChanged("Strasse");
            }
        }
        
        /// <remarks/>
        public string PLZ {
            get {
                return this.pLZField;
            }
            set {
                this.pLZField = value;
                this.RaisePropertyChanged("PLZ");
            }
        }
        
        /// <remarks/>
        public string Ort {
            get {
                return this.ortField;
            }
            set {
                this.ortField = value;
                this.RaisePropertyChanged("Ort");
            }
        }
        
        /// <remarks/>
        public string Telefon {
            get {
                return this.telefonField;
            }
            set {
                this.telefonField = value;
                this.RaisePropertyChanged("Telefon");
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.elster.de/2002/XMLSchema")]
    public partial class usta_SteuerfallCType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AdresseCType beraterField;
        
        private MandantCType mandantField;
        
        private AdresseCType unternehmerField;
        
        private object itemField;
        
        /// <remarks/>
        public AdresseCType Berater {
            get {
                return this.beraterField;
            }
            set {
                this.beraterField = value;
                this.RaisePropertyChanged("Berater");
            }
        }
        
        /// <remarks/>
        public MandantCType Mandant {
            get {
                return this.mandantField;
            }
            set {
                this.mandantField = value;
                this.RaisePropertyChanged("Mandant");
            }
        }
        
        /// <remarks/>
        public AdresseCType Unternehmer {
            get {
                return this.unternehmerField;
            }
            set {
                this.unternehmerField = value;
                this.RaisePropertyChanged("Unternehmer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Dauerfristverlaengerung", typeof(usta_DauerfristverlaengerungCType))]
        [System.Xml.Serialization.XmlElementAttribute("Umsatzsteuersondervorauszahlung", typeof(usta_UmsatzsteuersondervorauszahlungCType))]
        [System.Xml.Serialization.XmlElementAttribute("Umsatzsteuervoranmeldung", typeof(usta_UmsatzsteuervoranmeldungCType))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.elster.de/2002/XMLSchema")]
    public partial class AdresseCType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bezeichnungField;
        
        private string nameField;
        
        private string vornameField;
        
        private string namensvorsatzField;
        
        private string namenszusatzField;
        
        private string strField;
        
        private string hausnummerField;
        
        private string hNrZusatzField;
        
        private string anschriftenZusatzField;
        
        private string ortField;
        
        private string pLZField;
        
        private string auslandsPLZField;
        
        private string landField;
        
        private string postfachOrtField;
        
        private string postfachField;
        
        private string postfachPLZField;
        
        private string gKPLZField;
        
        private string telefonField;
        
        private string emailField;
        
        /// <remarks/>
        public string Bezeichnung {
            get {
                return this.bezeichnungField;
            }
            set {
                this.bezeichnungField = value;
                this.RaisePropertyChanged("Bezeichnung");
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        public string Vorname {
            get {
                return this.vornameField;
            }
            set {
                this.vornameField = value;
                this.RaisePropertyChanged("Vorname");
            }
        }
        
        /// <remarks/>
        public string Namensvorsatz {
            get {
                return this.namensvorsatzField;
            }
            set {
                this.namensvorsatzField = value;
                this.RaisePropertyChanged("Namensvorsatz");
            }
        }
        
        /// <remarks/>
        public string Namenszusatz {
            get {
                return this.namenszusatzField;
            }
            set {
                this.namenszusatzField = value;
                this.RaisePropertyChanged("Namenszusatz");
            }
        }
        
        /// <remarks/>
        public string Str {
            get {
                return this.strField;
            }
            set {
                this.strField = value;
                this.RaisePropertyChanged("Str");
            }
        }
        
        /// <remarks/>
        public string Hausnummer {
            get {
                return this.hausnummerField;
            }
            set {
                this.hausnummerField = value;
                this.RaisePropertyChanged("Hausnummer");
            }
        }
        
        /// <remarks/>
        public string HNrZusatz {
            get {
                return this.hNrZusatzField;
            }
            set {
                this.hNrZusatzField = value;
                this.RaisePropertyChanged("HNrZusatz");
            }
        }
        
        /// <remarks/>
        public string AnschriftenZusatz {
            get {
                return this.anschriftenZusatzField;
            }
            set {
                this.anschriftenZusatzField = value;
                this.RaisePropertyChanged("AnschriftenZusatz");
            }
        }
        
        /// <remarks/>
        public string Ort {
            get {
                return this.ortField;
            }
            set {
                this.ortField = value;
                this.RaisePropertyChanged("Ort");
            }
        }
        
        /// <remarks/>
        public string PLZ {
            get {
                return this.pLZField;
            }
            set {
                this.pLZField = value;
                this.RaisePropertyChanged("PLZ");
            }
        }
        
        /// <remarks/>
        public string AuslandsPLZ {
            get {
                return this.auslandsPLZField;
            }
            set {
                this.auslandsPLZField = value;
                this.RaisePropertyChanged("AuslandsPLZ");
            }
        }
        
        /// <remarks/>
        public string Land {
            get {
                return this.landField;
            }
            set {
                this.landField = value;
                this.RaisePropertyChanged("Land");
            }
        }
        
        /// <remarks/>
        public string PostfachOrt {
            get {
                return this.postfachOrtField;
            }
            set {
                this.postfachOrtField = value;
                this.RaisePropertyChanged("PostfachOrt");
            }
        }
        
        /// <remarks/>
        public string Postfach {
            get {
                return this.postfachField;
            }
            set {
                this.postfachField = value;
                this.RaisePropertyChanged("Postfach");
            }
        }
        
        /// <remarks/>
        public string PostfachPLZ {
            get {
                return this.postfachPLZField;
            }
            set {
                this.postfachPLZField = value;
                this.RaisePropertyChanged("PostfachPLZ");
            }
        }
        
        /// <remarks/>
        public string GKPLZ {
            get {
                return this.gKPLZField;
            }
            set {
                this.gKPLZField = value;
                this.RaisePropertyChanged("GKPLZ");
            }
        }
        
        /// <remarks/>
        public string Telefon {
            get {
                return this.telefonField;
            }
            set {
                this.telefonField = value;
                this.RaisePropertyChanged("Telefon");
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.elster.de/2002/XMLSchema")]
    public partial class MandantCType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string vornameField;
        
        private string mandantenNrField;
        
        private string bearbeiterkennzeichenField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        public string Vorname {
            get {
                return this.vornameField;
            }
            set {
                this.vornameField = value;
                this.RaisePropertyChanged("Vorname");
            }
        }
        
        /// <remarks/>
        public string MandantenNr {
            get {
                return this.mandantenNrField;
            }
            set {
                this.mandantenNrField = value;
                this.RaisePropertyChanged("MandantenNr");
            }
        }
        
        /// <remarks/>
        public string Bearbeiterkennzeichen {
            get {
                return this.bearbeiterkennzeichenField;
            }
            set {
                this.bearbeiterkennzeichenField = value;
                this.RaisePropertyChanged("Bearbeiterkennzeichen");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.elster.de/2002/XMLSchema")]
    public partial class usta_DauerfristverlaengerungCType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private usta_JahrSType jahrField;
        
        private string steuernummerField;
        
        private string kz09Field;
        
        /// <remarks/>
        public usta_JahrSType Jahr {
            get {
                return this.jahrField;
            }
            set {
                this.jahrField = value;
                this.RaisePropertyChanged("Jahr");
            }
        }
        
        /// <remarks/>
        public string Steuernummer {
            get {
                return this.steuernummerField;
            }
            set {
                this.steuernummerField = value;
                this.RaisePropertyChanged("Steuernummer");
            }
        }
        
        /// <remarks/>
        public string Kz09 {
            get {
                return this.kz09Field;
            }
            set {
                this.kz09Field = value;
                this.RaisePropertyChanged("Kz09");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.elster.de/2002/XMLSchema")]
    public enum usta_JahrSType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2012")]
        Item2012,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.elster.de/2002/XMLSchema")]
    public partial class usta_UmsatzsteuersondervorauszahlungCType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private usta_JahrSType jahrField;
        
        private string steuernummerField;
        
        private string kz09Field;
        
        private usta_Kz10SType kz10Field;
        
        private bool kz10FieldSpecified;
        
        private usta_Kz26SType kz26Field;
        
        private bool kz26FieldSpecified;
        
        private usta_Kz29SType kz29Field;
        
        private bool kz29FieldSpecified;
        
        private string kz38Field;
        
        /// <remarks/>
        public usta_JahrSType Jahr {
            get {
                return this.jahrField;
            }
            set {
                this.jahrField = value;
                this.RaisePropertyChanged("Jahr");
            }
        }
        
        /// <remarks/>
        public string Steuernummer {
            get {
                return this.steuernummerField;
            }
            set {
                this.steuernummerField = value;
                this.RaisePropertyChanged("Steuernummer");
            }
        }
        
        /// <remarks/>
        public string Kz09 {
            get {
                return this.kz09Field;
            }
            set {
                this.kz09Field = value;
                this.RaisePropertyChanged("Kz09");
            }
        }
        
        /// <remarks/>
        public usta_Kz10SType Kz10 {
            get {
                return this.kz10Field;
            }
            set {
                this.kz10Field = value;
                this.RaisePropertyChanged("Kz10");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Kz10Specified {
            get {
                return this.kz10FieldSpecified;
            }
            set {
                this.kz10FieldSpecified = value;
                this.RaisePropertyChanged("Kz10Specified");
            }
        }
        
        /// <remarks/>
        public usta_Kz26SType Kz26 {
            get {
                return this.kz26Field;
            }
            set {
                this.kz26Field = value;
                this.RaisePropertyChanged("Kz26");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Kz26Specified {
            get {
                return this.kz26FieldSpecified;
            }
            set {
                this.kz26FieldSpecified = value;
                this.RaisePropertyChanged("Kz26Specified");
            }
        }
        
        /// <remarks/>
        public usta_Kz29SType Kz29 {
            get {
                return this.kz29Field;
            }
            set {
                this.kz29Field = value;
                this.RaisePropertyChanged("Kz29");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Kz29Specified {
            get {
                return this.kz29FieldSpecified;
            }
            set {
                this.kz29FieldSpecified = value;
                this.RaisePropertyChanged("Kz29Specified");
            }
        }
        
        /// <remarks/>
        public string Kz38 {
            get {
                return this.kz38Field;
            }
            set {
                this.kz38Field = value;
                this.RaisePropertyChanged("Kz38");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.elster.de/2002/XMLSchema")]
    public enum usta_Kz10SType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.elster.de/2002/XMLSchema")]
    public enum usta_Kz26SType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.elster.de/2002/XMLSchema")]
    public enum usta_Kz29SType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.elster.de/2002/XMLSchema")]
    public partial class usta_UmsatzsteuervoranmeldungCType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private usta_JahrSType jahrField;
        
        private usta_ZeitraumSType zeitraumField;
        
        private string steuernummerField;
        
        private string kz09Field;
        
        private usta_Kz10SType kz10Field;
        
        private bool kz10FieldSpecified;
        
        private string kz21Field;
        
        private usta_Kz22SType kz22Field;
        
        private bool kz22FieldSpecified;
        
        private usta_Kz26SType kz26Field;
        
        private bool kz26FieldSpecified;
        
        private usta_Kz29SType kz29Field;
        
        private bool kz29FieldSpecified;
        
        private string kz35Field;
        
        private string kz36Field;
        
        private string kz39Field;
        
        private string kz41Field;
        
        private string kz42Field;
        
        private string kz43Field;
        
        private string kz44Field;
        
        private string kz45Field;
        
        private string kz46Field;
        
        private string kz47Field;
        
        private string kz48Field;
        
        private string kz49Field;
        
        private string kz52Field;
        
        private string kz53Field;
        
        private string kz59Field;
        
        private string kz60Field;
        
        private string kz61Field;
        
        private string kz62Field;
        
        private string kz63Field;
        
        private string kz64Field;
        
        private string kz65Field;
        
        private string kz66Field;
        
        private string kz67Field;
        
        private string kz68Field;
        
        private string kz69Field;
        
        private string kz73Field;
        
        private string kz74Field;
        
        private string kz76Field;
        
        private string kz77Field;
        
        private string kz78Field;
        
        private string kz79Field;
        
        private string kz80Field;
        
        private string kz81Field;
        
        private string kz83Field;
        
        private string kz84Field;
        
        private string kz85Field;
        
        private string kz86Field;
        
        private string kz89Field;
        
        private string kz91Field;
        
        private string kz93Field;
        
        private string kz94Field;
        
        private string kz95Field;
        
        private string kz96Field;
        
        private string kz98Field;
        
        /// <remarks/>
        public usta_JahrSType Jahr {
            get {
                return this.jahrField;
            }
            set {
                this.jahrField = value;
                this.RaisePropertyChanged("Jahr");
            }
        }
        
        /// <remarks/>
        public usta_ZeitraumSType Zeitraum {
            get {
                return this.zeitraumField;
            }
            set {
                this.zeitraumField = value;
                this.RaisePropertyChanged("Zeitraum");
            }
        }
        
        /// <remarks/>
        public string Steuernummer {
            get {
                return this.steuernummerField;
            }
            set {
                this.steuernummerField = value;
                this.RaisePropertyChanged("Steuernummer");
            }
        }
        
        /// <remarks/>
        public string Kz09 {
            get {
                return this.kz09Field;
            }
            set {
                this.kz09Field = value;
                this.RaisePropertyChanged("Kz09");
            }
        }
        
        /// <remarks/>
        public usta_Kz10SType Kz10 {
            get {
                return this.kz10Field;
            }
            set {
                this.kz10Field = value;
                this.RaisePropertyChanged("Kz10");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Kz10Specified {
            get {
                return this.kz10FieldSpecified;
            }
            set {
                this.kz10FieldSpecified = value;
                this.RaisePropertyChanged("Kz10Specified");
            }
        }
        
        /// <remarks/>
        public string Kz21 {
            get {
                return this.kz21Field;
            }
            set {
                this.kz21Field = value;
                this.RaisePropertyChanged("Kz21");
            }
        }
        
        /// <remarks/>
        public usta_Kz22SType Kz22 {
            get {
                return this.kz22Field;
            }
            set {
                this.kz22Field = value;
                this.RaisePropertyChanged("Kz22");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Kz22Specified {
            get {
                return this.kz22FieldSpecified;
            }
            set {
                this.kz22FieldSpecified = value;
                this.RaisePropertyChanged("Kz22Specified");
            }
        }
        
        /// <remarks/>
        public usta_Kz26SType Kz26 {
            get {
                return this.kz26Field;
            }
            set {
                this.kz26Field = value;
                this.RaisePropertyChanged("Kz26");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Kz26Specified {
            get {
                return this.kz26FieldSpecified;
            }
            set {
                this.kz26FieldSpecified = value;
                this.RaisePropertyChanged("Kz26Specified");
            }
        }
        
        /// <remarks/>
        public usta_Kz29SType Kz29 {
            get {
                return this.kz29Field;
            }
            set {
                this.kz29Field = value;
                this.RaisePropertyChanged("Kz29");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Kz29Specified {
            get {
                return this.kz29FieldSpecified;
            }
            set {
                this.kz29FieldSpecified = value;
                this.RaisePropertyChanged("Kz29Specified");
            }
        }
        
        /// <remarks/>
        public string Kz35 {
            get {
                return this.kz35Field;
            }
            set {
                this.kz35Field = value;
                this.RaisePropertyChanged("Kz35");
            }
        }
        
        /// <remarks/>
        public string Kz36 {
            get {
                return this.kz36Field;
            }
            set {
                this.kz36Field = value;
                this.RaisePropertyChanged("Kz36");
            }
        }
        
        /// <remarks/>
        public string Kz39 {
            get {
                return this.kz39Field;
            }
            set {
                this.kz39Field = value;
                this.RaisePropertyChanged("Kz39");
            }
        }
        
        /// <remarks/>
        public string Kz41 {
            get {
                return this.kz41Field;
            }
            set {
                this.kz41Field = value;
                this.RaisePropertyChanged("Kz41");
            }
        }
        
        /// <remarks/>
        public string Kz42 {
            get {
                return this.kz42Field;
            }
            set {
                this.kz42Field = value;
                this.RaisePropertyChanged("Kz42");
            }
        }
        
        /// <remarks/>
        public string Kz43 {
            get {
                return this.kz43Field;
            }
            set {
                this.kz43Field = value;
                this.RaisePropertyChanged("Kz43");
            }
        }
        
        /// <remarks/>
        public string Kz44 {
            get {
                return this.kz44Field;
            }
            set {
                this.kz44Field = value;
                this.RaisePropertyChanged("Kz44");
            }
        }
        
        /// <remarks/>
        public string Kz45 {
            get {
                return this.kz45Field;
            }
            set {
                this.kz45Field = value;
                this.RaisePropertyChanged("Kz45");
            }
        }
        
        /// <remarks/>
        public string Kz46 {
            get {
                return this.kz46Field;
            }
            set {
                this.kz46Field = value;
                this.RaisePropertyChanged("Kz46");
            }
        }
        
        /// <remarks/>
        public string Kz47 {
            get {
                return this.kz47Field;
            }
            set {
                this.kz47Field = value;
                this.RaisePropertyChanged("Kz47");
            }
        }
        
        /// <remarks/>
        public string Kz48 {
            get {
                return this.kz48Field;
            }
            set {
                this.kz48Field = value;
                this.RaisePropertyChanged("Kz48");
            }
        }
        
        /// <remarks/>
        public string Kz49 {
            get {
                return this.kz49Field;
            }
            set {
                this.kz49Field = value;
                this.RaisePropertyChanged("Kz49");
            }
        }
        
        /// <remarks/>
        public string Kz52 {
            get {
                return this.kz52Field;
            }
            set {
                this.kz52Field = value;
                this.RaisePropertyChanged("Kz52");
            }
        }
        
        /// <remarks/>
        public string Kz53 {
            get {
                return this.kz53Field;
            }
            set {
                this.kz53Field = value;
                this.RaisePropertyChanged("Kz53");
            }
        }
        
        /// <remarks/>
        public string Kz59 {
            get {
                return this.kz59Field;
            }
            set {
                this.kz59Field = value;
                this.RaisePropertyChanged("Kz59");
            }
        }
        
        /// <remarks/>
        public string Kz60 {
            get {
                return this.kz60Field;
            }
            set {
                this.kz60Field = value;
                this.RaisePropertyChanged("Kz60");
            }
        }
        
        /// <remarks/>
        public string Kz61 {
            get {
                return this.kz61Field;
            }
            set {
                this.kz61Field = value;
                this.RaisePropertyChanged("Kz61");
            }
        }
        
        /// <remarks/>
        public string Kz62 {
            get {
                return this.kz62Field;
            }
            set {
                this.kz62Field = value;
                this.RaisePropertyChanged("Kz62");
            }
        }
        
        /// <remarks/>
        public string Kz63 {
            get {
                return this.kz63Field;
            }
            set {
                this.kz63Field = value;
                this.RaisePropertyChanged("Kz63");
            }
        }
        
        /// <remarks/>
        public string Kz64 {
            get {
                return this.kz64Field;
            }
            set {
                this.kz64Field = value;
                this.RaisePropertyChanged("Kz64");
            }
        }
        
        /// <remarks/>
        public string Kz65 {
            get {
                return this.kz65Field;
            }
            set {
                this.kz65Field = value;
                this.RaisePropertyChanged("Kz65");
            }
        }
        
        /// <remarks/>
        public string Kz66 {
            get {
                return this.kz66Field;
            }
            set {
                this.kz66Field = value;
                this.RaisePropertyChanged("Kz66");
            }
        }
        
        /// <remarks/>
        public string Kz67 {
            get {
                return this.kz67Field;
            }
            set {
                this.kz67Field = value;
                this.RaisePropertyChanged("Kz67");
            }
        }
        
        /// <remarks/>
        public string Kz68 {
            get {
                return this.kz68Field;
            }
            set {
                this.kz68Field = value;
                this.RaisePropertyChanged("Kz68");
            }
        }
        
        /// <remarks/>
        public string Kz69 {
            get {
                return this.kz69Field;
            }
            set {
                this.kz69Field = value;
                this.RaisePropertyChanged("Kz69");
            }
        }
        
        /// <remarks/>
        public string Kz73 {
            get {
                return this.kz73Field;
            }
            set {
                this.kz73Field = value;
                this.RaisePropertyChanged("Kz73");
            }
        }
        
        /// <remarks/>
        public string Kz74 {
            get {
                return this.kz74Field;
            }
            set {
                this.kz74Field = value;
                this.RaisePropertyChanged("Kz74");
            }
        }
        
        /// <remarks/>
        public string Kz76 {
            get {
                return this.kz76Field;
            }
            set {
                this.kz76Field = value;
                this.RaisePropertyChanged("Kz76");
            }
        }
        
        /// <remarks/>
        public string Kz77 {
            get {
                return this.kz77Field;
            }
            set {
                this.kz77Field = value;
                this.RaisePropertyChanged("Kz77");
            }
        }
        
        /// <remarks/>
        public string Kz78 {
            get {
                return this.kz78Field;
            }
            set {
                this.kz78Field = value;
                this.RaisePropertyChanged("Kz78");
            }
        }
        
        /// <remarks/>
        public string Kz79 {
            get {
                return this.kz79Field;
            }
            set {
                this.kz79Field = value;
                this.RaisePropertyChanged("Kz79");
            }
        }
        
        /// <remarks/>
        public string Kz80 {
            get {
                return this.kz80Field;
            }
            set {
                this.kz80Field = value;
                this.RaisePropertyChanged("Kz80");
            }
        }
        
        /// <remarks/>
        public string Kz81 {
            get {
                return this.kz81Field;
            }
            set {
                this.kz81Field = value;
                this.RaisePropertyChanged("Kz81");
            }
        }
        
        /// <remarks/>
        public string Kz83 {
            get {
                return this.kz83Field;
            }
            set {
                this.kz83Field = value;
                this.RaisePropertyChanged("Kz83");
            }
        }
        
        /// <remarks/>
        public string Kz84 {
            get {
                return this.kz84Field;
            }
            set {
                this.kz84Field = value;
                this.RaisePropertyChanged("Kz84");
            }
        }
        
        /// <remarks/>
        public string Kz85 {
            get {
                return this.kz85Field;
            }
            set {
                this.kz85Field = value;
                this.RaisePropertyChanged("Kz85");
            }
        }
        
        /// <remarks/>
        public string Kz86 {
            get {
                return this.kz86Field;
            }
            set {
                this.kz86Field = value;
                this.RaisePropertyChanged("Kz86");
            }
        }
        
        /// <remarks/>
        public string Kz89 {
            get {
                return this.kz89Field;
            }
            set {
                this.kz89Field = value;
                this.RaisePropertyChanged("Kz89");
            }
        }
        
        /// <remarks/>
        public string Kz91 {
            get {
                return this.kz91Field;
            }
            set {
                this.kz91Field = value;
                this.RaisePropertyChanged("Kz91");
            }
        }
        
        /// <remarks/>
        public string Kz93 {
            get {
                return this.kz93Field;
            }
            set {
                this.kz93Field = value;
                this.RaisePropertyChanged("Kz93");
            }
        }
        
        /// <remarks/>
        public string Kz94 {
            get {
                return this.kz94Field;
            }
            set {
                this.kz94Field = value;
                this.RaisePropertyChanged("Kz94");
            }
        }
        
        /// <remarks/>
        public string Kz95 {
            get {
                return this.kz95Field;
            }
            set {
                this.kz95Field = value;
                this.RaisePropertyChanged("Kz95");
            }
        }
        
        /// <remarks/>
        public string Kz96 {
            get {
                return this.kz96Field;
            }
            set {
                this.kz96Field = value;
                this.RaisePropertyChanged("Kz96");
            }
        }
        
        /// <remarks/>
        public string Kz98 {
            get {
                return this.kz98Field;
            }
            set {
                this.kz98Field = value;
                this.RaisePropertyChanged("Kz98");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.elster.de/2002/XMLSchema")]
    public enum usta_ZeitraumSType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01")]
        Item01,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02")]
        Item02,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03")]
        Item03,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("04")]
        Item04,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("05")]
        Item05,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("06")]
        Item06,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("07")]
        Item07,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("08")]
        Item08,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09")]
        Item09,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("11")]
        Item11,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("12")]
        Item12,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("41")]
        Item41,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("42")]
        Item42,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("43")]
        Item43,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("44")]
        Item44,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.elster.de/2002/XMLSchema")]
    public enum usta_Kz22SType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.elster.de/2002/XMLSchema")]
    public enum usta_AnmeldungssteuernCTypeVersion {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("201201")]
        Item201201,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.elster.de/2002/XMLSchema")]
    public partial class NutzdatenblockCType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private NutzdatenHeaderCType nutzdatenHeaderField;
        
        private NutzdatenCType nutzdatenField;
        
        /// <remarks/>
        public NutzdatenHeaderCType NutzdatenHeader {
            get {
                return this.nutzdatenHeaderField;
            }
            set {
                this.nutzdatenHeaderField = value;
                this.RaisePropertyChanged("NutzdatenHeader");
            }
        }
        
        /// <remarks/>
        public NutzdatenCType Nutzdaten {
            get {
                return this.nutzdatenField;
            }
            set {
                this.nutzdatenField = value;
                this.RaisePropertyChanged("Nutzdaten");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.elster.de/2002/XMLSchema")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.elster.de/2002/XMLSchema", IsNullable=false)]
    public partial class Elster : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TransferHeaderCType transferHeaderField;
        
        private NutzdatenblockCType[] datenTeilField;
        
        /// <remarks/>
        public TransferHeaderCType TransferHeader {
            get {
                return this.transferHeaderField;
            }
            set {
                this.transferHeaderField = value;
                this.RaisePropertyChanged("TransferHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Nutzdatenblock", IsNullable=false)]
        public NutzdatenblockCType[] DatenTeil {
            get {
                return this.datenTeilField;
            }
            set {
                this.datenTeilField = value;
                this.RaisePropertyChanged("DatenTeil");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
