//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.6.1055.0.
// 
namespace Dataline.Elster.Anmeldung.LStA201601 {
    using System.Xml.Serialization;
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThrough()]
    [XmlType(Namespace="http://www.elster.de/2002/XMLSchema")]
    public partial class AnmeldungssteuernCType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private lstaDatenlieferantType datenLieferantField;
        
        private string erstellungsdatumField;
        
        private lstaSteuerfallType steuerfallField;
        
        private string artField;
        
        private AnmeldungssteuernCTypeVersion versionField;
        
        public AnmeldungssteuernCType() {
            artField = "LStA";
        }
        
        /// <remarks/>
        public lstaDatenlieferantType DatenLieferant {
            get {
                return datenLieferantField;
            }
            set {
                datenLieferantField = value;
                RaisePropertyChanged("DatenLieferant");
            }
        }
        
        /// <remarks/>
        public string Erstellungsdatum {
            get {
                return erstellungsdatumField;
            }
            set {
                erstellungsdatumField = value;
                RaisePropertyChanged("Erstellungsdatum");
            }
        }
        
        /// <remarks/>
        public lstaSteuerfallType Steuerfall {
            get {
                return steuerfallField;
            }
            set {
                steuerfallField = value;
                RaisePropertyChanged("Steuerfall");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string art {
            get {
                return artField;
            }
            set {
                artField = value;
                RaisePropertyChanged("art");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AnmeldungssteuernCTypeVersion version {
            get {
                return versionField;
            }
            set {
                versionField = value;
                RaisePropertyChanged("version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThrough()]
    [XmlType(Namespace="http://www.elster.de/2002/XMLSchema")]
    public partial class lstaDatenlieferantType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string strasseField;
        
        private string pLZField;
        
        private string ortField;
        
        private string telefonField;
        
        private string emailField;
        
        /// <remarks/>
        public string Name {
            get {
                return nameField;
            }
            set {
                nameField = value;
                RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        public string Strasse {
            get {
                return strasseField;
            }
            set {
                strasseField = value;
                RaisePropertyChanged("Strasse");
            }
        }
        
        /// <remarks/>
        public string PLZ {
            get {
                return pLZField;
            }
            set {
                pLZField = value;
                RaisePropertyChanged("PLZ");
            }
        }
        
        /// <remarks/>
        public string Ort {
            get {
                return ortField;
            }
            set {
                ortField = value;
                RaisePropertyChanged("Ort");
            }
        }
        
        /// <remarks/>
        public string Telefon {
            get {
                return telefonField;
            }
            set {
                telefonField = value;
                RaisePropertyChanged("Telefon");
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return emailField;
            }
            set {
                emailField = value;
                RaisePropertyChanged("Email");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThrough()]
    [XmlType(Namespace="http://www.elster.de/2002/XMLSchema")]
    public partial class lstaSteuerfallType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AdresseCType beraterField;
        
        private MandantCType mandantField;
        
        private AdresseCType unternehmerField;
        
        private lstaSteuerfallTypeLohnsteueranmeldung lohnsteueranmeldungField;
        
        /// <remarks/>
        public AdresseCType Berater {
            get {
                return beraterField;
            }
            set {
                beraterField = value;
                RaisePropertyChanged("Berater");
            }
        }
        
        /// <remarks/>
        public MandantCType Mandant {
            get {
                return mandantField;
            }
            set {
                mandantField = value;
                RaisePropertyChanged("Mandant");
            }
        }
        
        /// <remarks/>
        public AdresseCType Unternehmer {
            get {
                return unternehmerField;
            }
            set {
                unternehmerField = value;
                RaisePropertyChanged("Unternehmer");
            }
        }
        
        /// <remarks/>
        public lstaSteuerfallTypeLohnsteueranmeldung Lohnsteueranmeldung {
            get {
                return lohnsteueranmeldungField;
            }
            set {
                lohnsteueranmeldungField = value;
                RaisePropertyChanged("Lohnsteueranmeldung");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThrough()]
    [XmlType(Namespace="http://www.elster.de/2002/XMLSchema")]
    public partial class AdresseCType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bezeichnungField;
        
        private string nameField;
        
        private string vornameField;
        
        private string namensvorsatzField;
        
        private string namenszusatzField;
        
        private string strField;
        
        private string hausnummerField;
        
        private string hNrZusatzField;
        
        private string anschriftenZusatzField;
        
        private string ortField;
        
        private string pLZField;
        
        private string auslandsPLZField;
        
        private string landField;
        
        private string postfachOrtField;
        
        private string postfachField;
        
        private string postfachPLZField;
        
        private string gKPLZField;
        
        private string telefonField;
        
        private string emailField;
        
        /// <remarks/>
        public string Bezeichnung {
            get {
                return bezeichnungField;
            }
            set {
                bezeichnungField = value;
                RaisePropertyChanged("Bezeichnung");
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return nameField;
            }
            set {
                nameField = value;
                RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        public string Vorname {
            get {
                return vornameField;
            }
            set {
                vornameField = value;
                RaisePropertyChanged("Vorname");
            }
        }
        
        /// <remarks/>
        public string Namensvorsatz {
            get {
                return namensvorsatzField;
            }
            set {
                namensvorsatzField = value;
                RaisePropertyChanged("Namensvorsatz");
            }
        }
        
        /// <remarks/>
        public string Namenszusatz {
            get {
                return namenszusatzField;
            }
            set {
                namenszusatzField = value;
                RaisePropertyChanged("Namenszusatz");
            }
        }
        
        /// <remarks/>
        public string Str {
            get {
                return strField;
            }
            set {
                strField = value;
                RaisePropertyChanged("Str");
            }
        }
        
        /// <remarks/>
        public string Hausnummer {
            get {
                return hausnummerField;
            }
            set {
                hausnummerField = value;
                RaisePropertyChanged("Hausnummer");
            }
        }
        
        /// <remarks/>
        public string HNrZusatz {
            get {
                return hNrZusatzField;
            }
            set {
                hNrZusatzField = value;
                RaisePropertyChanged("HNrZusatz");
            }
        }
        
        /// <remarks/>
        public string AnschriftenZusatz {
            get {
                return anschriftenZusatzField;
            }
            set {
                anschriftenZusatzField = value;
                RaisePropertyChanged("AnschriftenZusatz");
            }
        }
        
        /// <remarks/>
        public string Ort {
            get {
                return ortField;
            }
            set {
                ortField = value;
                RaisePropertyChanged("Ort");
            }
        }
        
        /// <remarks/>
        public string PLZ {
            get {
                return pLZField;
            }
            set {
                pLZField = value;
                RaisePropertyChanged("PLZ");
            }
        }
        
        /// <remarks/>
        public string AuslandsPLZ {
            get {
                return auslandsPLZField;
            }
            set {
                auslandsPLZField = value;
                RaisePropertyChanged("AuslandsPLZ");
            }
        }
        
        /// <remarks/>
        public string Land {
            get {
                return landField;
            }
            set {
                landField = value;
                RaisePropertyChanged("Land");
            }
        }
        
        /// <remarks/>
        public string PostfachOrt {
            get {
                return postfachOrtField;
            }
            set {
                postfachOrtField = value;
                RaisePropertyChanged("PostfachOrt");
            }
        }
        
        /// <remarks/>
        public string Postfach {
            get {
                return postfachField;
            }
            set {
                postfachField = value;
                RaisePropertyChanged("Postfach");
            }
        }
        
        /// <remarks/>
        public string PostfachPLZ {
            get {
                return postfachPLZField;
            }
            set {
                postfachPLZField = value;
                RaisePropertyChanged("PostfachPLZ");
            }
        }
        
        /// <remarks/>
        public string GKPLZ {
            get {
                return gKPLZField;
            }
            set {
                gKPLZField = value;
                RaisePropertyChanged("GKPLZ");
            }
        }
        
        /// <remarks/>
        public string Telefon {
            get {
                return telefonField;
            }
            set {
                telefonField = value;
                RaisePropertyChanged("Telefon");
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return emailField;
            }
            set {
                emailField = value;
                RaisePropertyChanged("Email");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThrough()]
    [XmlType(Namespace="http://www.elster.de/2002/XMLSchema")]
    public partial class MandantCType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string vornameField;
        
        private string mandantenNrField;
        
        private string bearbeiterkennzeichenField;
        
        /// <remarks/>
        public string Name {
            get {
                return nameField;
            }
            set {
                nameField = value;
                RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        public string Vorname {
            get {
                return vornameField;
            }
            set {
                vornameField = value;
                RaisePropertyChanged("Vorname");
            }
        }
        
        /// <remarks/>
        public string MandantenNr {
            get {
                return mandantenNrField;
            }
            set {
                mandantenNrField = value;
                RaisePropertyChanged("MandantenNr");
            }
        }
        
        /// <remarks/>
        public string Bearbeiterkennzeichen {
            get {
                return bearbeiterkennzeichenField;
            }
            set {
                bearbeiterkennzeichenField = value;
                RaisePropertyChanged("Bearbeiterkennzeichen");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThrough()]
    [XmlType(AnonymousType=true, Namespace="http://www.elster.de/2002/XMLSchema")]
    public partial class lstaSteuerfallTypeLohnsteueranmeldung : object, System.ComponentModel.INotifyPropertyChanged {
        
        private lstaJahrSType jahrField;
        
        private lstaZeitraumSType zeitraumField;
        
        private string steuernummerField;
        
        private string kz09Field;
        
        private Kz10 kz10Field;
        
        private bool kz10FieldSpecified;
        
        private Kz26 kz26Field;
        
        private bool kz26FieldSpecified;
        
        private Kz29 kz29Field;
        
        private bool kz29FieldSpecified;
        
        private string kz33Field;
        
        private string kz41Field;
        
        private string kz42Field;
        
        private string kz43Field;
        
        private string kz44Field;
        
        private string kz47Field;
        
        private string kz48Field;
        
        private string kz49Field;
        
        private string kz61Field;
        
        private string kz62Field;
        
        private string kz63Field;
        
        private string kz64Field;
        
        private string kz65Field;
        
        private string kz66Field;
        
        private string kz67Field;
        
        private string kz68Field;
        
        private string kz70Field;
        
        private string kz72Field;
        
        private string kz73Field;
        
        private string kz74Field;
        
        private string kz78Field;
        
        private string kz83Field;
        
        private string kz86Field;
        
        /// <remarks/>
        public lstaJahrSType Jahr {
            get {
                return jahrField;
            }
            set {
                jahrField = value;
                RaisePropertyChanged("Jahr");
            }
        }
        
        /// <remarks/>
        public lstaZeitraumSType Zeitraum {
            get {
                return zeitraumField;
            }
            set {
                zeitraumField = value;
                RaisePropertyChanged("Zeitraum");
            }
        }
        
        /// <remarks/>
        public string Steuernummer {
            get {
                return steuernummerField;
            }
            set {
                steuernummerField = value;
                RaisePropertyChanged("Steuernummer");
            }
        }
        
        /// <remarks/>
        public string Kz09 {
            get {
                return kz09Field;
            }
            set {
                kz09Field = value;
                RaisePropertyChanged("Kz09");
            }
        }
        
        /// <remarks/>
        public Kz10 Kz10 {
            get {
                return kz10Field;
            }
            set {
                kz10Field = value;
                RaisePropertyChanged("Kz10");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Kz10Specified {
            get {
                return kz10FieldSpecified;
            }
            set {
                kz10FieldSpecified = value;
                RaisePropertyChanged("Kz10Specified");
            }
        }
        
        /// <remarks/>
        public Kz26 Kz26 {
            get {
                return kz26Field;
            }
            set {
                kz26Field = value;
                RaisePropertyChanged("Kz26");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Kz26Specified {
            get {
                return kz26FieldSpecified;
            }
            set {
                kz26FieldSpecified = value;
                RaisePropertyChanged("Kz26Specified");
            }
        }
        
        /// <remarks/>
        public Kz29 Kz29 {
            get {
                return kz29Field;
            }
            set {
                kz29Field = value;
                RaisePropertyChanged("Kz29");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Kz29Specified {
            get {
                return kz29FieldSpecified;
            }
            set {
                kz29FieldSpecified = value;
                RaisePropertyChanged("Kz29Specified");
            }
        }
        
        /// <remarks/>
        public string Kz33 {
            get {
                return kz33Field;
            }
            set {
                kz33Field = value;
                RaisePropertyChanged("Kz33");
            }
        }
        
        /// <remarks/>
        public string Kz41 {
            get {
                return kz41Field;
            }
            set {
                kz41Field = value;
                RaisePropertyChanged("Kz41");
            }
        }
        
        /// <remarks/>
        public string Kz42 {
            get {
                return kz42Field;
            }
            set {
                kz42Field = value;
                RaisePropertyChanged("Kz42");
            }
        }
        
        /// <remarks/>
        public string Kz43 {
            get {
                return kz43Field;
            }
            set {
                kz43Field = value;
                RaisePropertyChanged("Kz43");
            }
        }
        
        /// <remarks/>
        public string Kz44 {
            get {
                return kz44Field;
            }
            set {
                kz44Field = value;
                RaisePropertyChanged("Kz44");
            }
        }
        
        /// <remarks/>
        public string Kz47 {
            get {
                return kz47Field;
            }
            set {
                kz47Field = value;
                RaisePropertyChanged("Kz47");
            }
        }
        
        /// <remarks/>
        public string Kz48 {
            get {
                return kz48Field;
            }
            set {
                kz48Field = value;
                RaisePropertyChanged("Kz48");
            }
        }
        
        /// <remarks/>
        public string Kz49 {
            get {
                return kz49Field;
            }
            set {
                kz49Field = value;
                RaisePropertyChanged("Kz49");
            }
        }
        
        /// <remarks/>
        public string Kz61 {
            get {
                return kz61Field;
            }
            set {
                kz61Field = value;
                RaisePropertyChanged("Kz61");
            }
        }
        
        /// <remarks/>
        public string Kz62 {
            get {
                return kz62Field;
            }
            set {
                kz62Field = value;
                RaisePropertyChanged("Kz62");
            }
        }
        
        /// <remarks/>
        public string Kz63 {
            get {
                return kz63Field;
            }
            set {
                kz63Field = value;
                RaisePropertyChanged("Kz63");
            }
        }
        
        /// <remarks/>
        public string Kz64 {
            get {
                return kz64Field;
            }
            set {
                kz64Field = value;
                RaisePropertyChanged("Kz64");
            }
        }
        
        /// <remarks/>
        public string Kz65 {
            get {
                return kz65Field;
            }
            set {
                kz65Field = value;
                RaisePropertyChanged("Kz65");
            }
        }
        
        /// <remarks/>
        public string Kz66 {
            get {
                return kz66Field;
            }
            set {
                kz66Field = value;
                RaisePropertyChanged("Kz66");
            }
        }
        
        /// <remarks/>
        public string Kz67 {
            get {
                return kz67Field;
            }
            set {
                kz67Field = value;
                RaisePropertyChanged("Kz67");
            }
        }
        
        /// <remarks/>
        public string Kz68 {
            get {
                return kz68Field;
            }
            set {
                kz68Field = value;
                RaisePropertyChanged("Kz68");
            }
        }
        
        /// <remarks/>
        public string Kz70 {
            get {
                return kz70Field;
            }
            set {
                kz70Field = value;
                RaisePropertyChanged("Kz70");
            }
        }
        
        /// <remarks/>
        public string Kz72 {
            get {
                return kz72Field;
            }
            set {
                kz72Field = value;
                RaisePropertyChanged("Kz72");
            }
        }
        
        /// <remarks/>
        public string Kz73 {
            get {
                return kz73Field;
            }
            set {
                kz73Field = value;
                RaisePropertyChanged("Kz73");
            }
        }
        
        /// <remarks/>
        public string Kz74 {
            get {
                return kz74Field;
            }
            set {
                kz74Field = value;
                RaisePropertyChanged("Kz74");
            }
        }
        
        /// <remarks/>
        public string Kz78 {
            get {
                return kz78Field;
            }
            set {
                kz78Field = value;
                RaisePropertyChanged("Kz78");
            }
        }
        
        /// <remarks/>
        public string Kz83 {
            get {
                return kz83Field;
            }
            set {
                kz83Field = value;
                RaisePropertyChanged("Kz83");
            }
        }
        
        /// <remarks/>
        public string Kz86 {
            get {
                return kz86Field;
            }
            set {
                kz86Field = value;
                RaisePropertyChanged("Kz86");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.6.1055.0")]
    [XmlType(Namespace="http://www.elster.de/2002/XMLSchema")]
    public enum lstaJahrSType {
        
        /// <remarks/>
        [XmlEnum("2016")]
        Item2016,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.6.1055.0")]
    [XmlType(Namespace="http://www.elster.de/2002/XMLSchema")]
    public enum lstaZeitraumSType {
        
        /// <remarks/>
        [XmlEnum("01")]
        Item01,
        
        /// <remarks/>
        [XmlEnum("02")]
        Item02,
        
        /// <remarks/>
        [XmlEnum("03")]
        Item03,
        
        /// <remarks/>
        [XmlEnum("04")]
        Item04,
        
        /// <remarks/>
        [XmlEnum("05")]
        Item05,
        
        /// <remarks/>
        [XmlEnum("06")]
        Item06,
        
        /// <remarks/>
        [XmlEnum("07")]
        Item07,
        
        /// <remarks/>
        [XmlEnum("08")]
        Item08,
        
        /// <remarks/>
        [XmlEnum("09")]
        Item09,
        
        /// <remarks/>
        [XmlEnum("10")]
        Item10,
        
        /// <remarks/>
        [XmlEnum("11")]
        Item11,
        
        /// <remarks/>
        [XmlEnum("12")]
        Item12,
        
        /// <remarks/>
        [XmlEnum("19")]
        Item19,
        
        /// <remarks/>
        [XmlEnum("41")]
        Item41,
        
        /// <remarks/>
        [XmlEnum("42")]
        Item42,
        
        /// <remarks/>
        [XmlEnum("43")]
        Item43,
        
        /// <remarks/>
        [XmlEnum("44")]
        Item44,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.6.1055.0")]
    [XmlType(Namespace="http://www.elster.de/2002/XMLSchema")]
    public enum Kz10 {
        
        /// <remarks/>
        [XmlEnum("1")]
        Item1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.6.1055.0")]
    [XmlType(Namespace="http://www.elster.de/2002/XMLSchema")]
    public enum Kz26 {
        
        /// <remarks/>
        [XmlEnum("1")]
        Item1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.6.1055.0")]
    [XmlType(Namespace="http://www.elster.de/2002/XMLSchema")]
    public enum Kz29 {
        
        /// <remarks/>
        [XmlEnum("1")]
        Item1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.6.1055.0")]
    [XmlType(AnonymousType=true, Namespace="http://www.elster.de/2002/XMLSchema")]
    public enum AnmeldungssteuernCTypeVersion {
        
        /// <remarks/>
        [XmlEnum("201601")]
        Item201601,
    }
}
