//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34003
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.0.30319.33440.
// 
namespace Dataline.Elster.Lohn {
    using System.Xml.Serialization;
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(Namespace="http://www.elster.de/2002/XMLSchema")]
    public partial class NutzdatenCType: object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.Generic.List<object> itemsField;
        
        /// <remarks/>
        [XmlElement("Protokoll", typeof(ProtokollCType))]
        [XmlElement("ProtokollAnforderung", typeof(ProtokollAnforderungCType))]
        [XmlElement("ProtokollAnforderung", typeof(Protocol3.ProtokollAnforderungCType), Namespace="http://www.elsterfachmethodik.de/protokollverfahren/version3/XMLSchema")]
        [XmlElement("Protokoll", typeof(Protocol4.ProtokollCType), Namespace="http://www.elsterfachmethodik.de/protokollverfahren/version4/XMLSchema")]
        [XmlElement("Protokoll", typeof(Protocol5.ProtokollCType), Namespace="http://www.elsterfachmethodik.de/protokollverfahren/version5/XMLSchema")]
        [XmlElement("Lohnsteuerbescheinigung", typeof(LStB200901.lstb_LohnsteuerbescheinigungCType), Namespace = "http://www.elsterlohn.de/2009-01/XMLSchema")]
        [XmlElement("Lohnsteuerbescheinigung", typeof(LStB201001.lstb_LohnsteuerbescheinigungCType), Namespace = "http://www.elsterlohn.de/2010-01/XMLSchema")]
        [XmlElement("Lohnsteuerbescheinigung", typeof(LStB201101.lstb_LohnsteuerbescheinigungCType), Namespace = "http://www.elsterlohn.de/2011-01/XMLSchema")]
        [XmlElement("Lohnsteuerbescheinigung", typeof(LStB201201.lstb_LohnsteuerbescheinigungCType), Namespace="http://www.elsterlohn.de/2012-01/XMLSchema")]
        [XmlElement("Lohnsteuerbescheinigung", typeof(LStB201301.lstb_LohnsteuerbescheinigungCType), Namespace="http://www.elsterlohn.de/2013-01/XMLSchema")]
        [XmlElement("Lohnsteuerbescheinigung", typeof(LStB201302.lstb_LohnsteuerbescheinigungCType), Namespace="http://www.elsterlohn.de/2013-02/XMLSchema")]
        [XmlElement("Lohnsteuerbescheinigung", typeof(LStB201401.lstb_LohnsteuerbescheinigungCType), Namespace="http://www.elsterlohn.de/2014-01/XMLSchema")]
        [XmlElement("Lohnsteuerbescheinigung", typeof(LStB201501.lstb_LohnsteuerbescheinigungCType), Namespace = "http://www.elsterlohn.de/2015-01/XMLSchema")]
        [XmlElement("Lohnsteuerbescheinigung", typeof(LStB201601.lstb_LohnsteuerbescheinigungCType), Namespace = "http://www.elsterlohn.de/2016-01/XMLSchema")]
        public System.Collections.Generic.List<object> Items
        {
            get {
                return itemsField;
            }
            set {
                itemsField = value;
                RaisePropertyChanged("Items");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}