//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34003
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.0.30319.33440.
// 

using Dataline.Elster.Basis;

namespace Dataline.Elster.Lohn {
    using System.Xml.Serialization;
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(Namespace="http://www.elster.de/2002/XMLSchema")]
    public partial class NutzdatenblockCType: object, System.ComponentModel.INotifyPropertyChanged {
        
        private NutzdatenHeaderCType nutzdatenHeaderField;
        
        private NutzdatenCType nutzdatenField;
        
        /// <remarks/>
        public NutzdatenHeaderCType NutzdatenHeader {
            get {
                return nutzdatenHeaderField;
            }
            set {
                nutzdatenHeaderField = value;
                RaisePropertyChanged("NutzdatenHeader");
            }
        }
        
        /// <remarks/>
        public NutzdatenCType Nutzdaten {
            get {
                return nutzdatenField;
            }
            set {
                nutzdatenField = value;
                RaisePropertyChanged("Nutzdaten");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}