//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34003
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.0.30319.33440.
// 
namespace Dataline.Elster.Lohn
{
    using System.Xml.Serialization;
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.elster.de/2002/XMLSchema")]
    [System.Xml.Serialization.XmlRootAttribute("Protokoll", Namespace="http://www.elster.de/2002/XMLSchema", IsNullable=false)]
    public partial class ProtokollCType: object, System.ComponentModel.INotifyPropertyChanged {
        
        private string zeitStempelField;
        
        private DatenTeilStatusCType datenTeilStatusField;
        
        private string versionField;
        
        /// <remarks/>
        public string ZeitStempel {
            get {
                return this.zeitStempelField;
            }
            set {
                this.zeitStempelField = value;
                this.RaisePropertyChanged("ZeitStempel");
            }
        }
        
        /// <remarks/>
        public DatenTeilStatusCType DatenTeilStatus {
            get {
                return this.datenTeilStatusField;
            }
            set {
                this.datenTeilStatusField = value;
                this.RaisePropertyChanged("DatenTeilStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}