//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// <copyright file="lstb_AdresseCType.cs" company="DATALINE GmbH &amp; Co. KG">
// Copyright (c) DATALINE GmbH &amp; Co. KG. All rights reserved.
// </copyright>

using System.Xml.Serialization;

namespace Dataline.Elster.Lohn.LStB200901
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlTypeAttribute(Namespace = "http://www.elsterlohn.de/2009-01/XMLSchema")]
    public partial class lstb_AdresseCType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string strField;

        private string hausnummerField;

        private string hNrZusatzField;

        private string anschriftenzusatzField;

        private string ortField;

        private object itemField;

        private string postfachOrtField;

        private string postfachField;

        private string postfachPLZField;

        /// <remarks/>
        public string Str
        {
            get
            {
                return this.strField;
            }
            set
            {
                this.strField = value;
                this.RaisePropertyChanged("Str");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string Hausnummer
        {
            get
            {
                return this.hausnummerField;
            }
            set
            {
                this.hausnummerField = value;
                this.RaisePropertyChanged("Hausnummer");
            }
        }

        /// <remarks/>
        public string HNrZusatz
        {
            get
            {
                return this.hNrZusatzField;
            }
            set
            {
                this.hNrZusatzField = value;
                this.RaisePropertyChanged("HNrZusatz");
            }
        }

        /// <remarks/>
        public string Anschriftenzusatz
        {
            get
            {
                return this.anschriftenzusatzField;
            }
            set
            {
                this.anschriftenzusatzField = value;
                this.RaisePropertyChanged("Anschriftenzusatz");
            }
        }

        /// <remarks/>
        public string Ort
        {
            get
            {
                return this.ortField;
            }
            set
            {
                this.ortField = value;
                this.RaisePropertyChanged("Ort");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AuslandsPLZ", typeof(LStB200901.AuslandsPLZCType))]
        [System.Xml.Serialization.XmlElementAttribute("PLZ", typeof(string), DataType = "positiveInteger")]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }

        /// <remarks/>
        public string PostfachOrt
        {
            get
            {
                return this.postfachOrtField;
            }
            set
            {
                this.postfachOrtField = value;
                this.RaisePropertyChanged("PostfachOrt");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "positiveInteger")]
        public string Postfach
        {
            get
            {
                return this.postfachField;
            }
            set
            {
                this.postfachField = value;
                this.RaisePropertyChanged("Postfach");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "positiveInteger")]
        public string PostfachPLZ
        {
            get
            {
                return this.postfachPLZField;
            }
            set
            {
                this.postfachPLZField = value;
                this.RaisePropertyChanged("PostfachPLZ");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
