//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// <copyright file="lstb_BesteuerungsgrundlagenCType.cs" company="DATALINE GmbH &amp; Co. KG">
// Copyright (c) DATALINE GmbH &amp; Co. KG. All rights reserved.
// </copyright>

using System.Linq;
using System.Xml.Serialization;

namespace Dataline.Elster.Lohn
{
    namespace LStB200901
    {
        public partial class lstb_BesteuerungsgrundlagenCType
        {
            /// <remarks/>
            [XmlIgnore]
            public bool LSteuerMKalJahrSpecified { get; set; }

            /// <remarks/>
            [XmlIgnore]
            public bool SoliMKalJahrSpecified { get; set; }

            [XmlIgnore]
            public decimal StBegVBezGesamt
            {
                get
                {
                    if (StBegVBez == null || StBegVBez.Count == 0)
                        return 0m;
                    return StBegVBez.Sum(x => x.Value);
                }
            }

            [XmlIgnore]
            public decimal StBegVBezBemGrFreibetragGesamt
            {
                get
                {
                    if (StBegVBez == null || StBegVBez.Count == 0)
                        return 0m;
                    return StBegVBez.Sum(x => x.bmgfreibetrag);
                }
            }

            [XmlIgnore]
            public decimal StBegVBezEinmVersBezugGesamt
            {
                get
                {
                    if (StBegVBez == null || StBegVBez.Count == 0)
                        return 0m;
                    return StBegVBez.Where(x => x.einmversbezugSpecified).Sum(x => x.einmversbezug);
                }
            }

            /// <summary>
            /// Gesamt-Wert von: Ermäßigt besteuerte Versorgungsbezüge für mehrere Kalenderjahre
            /// </summary>
            [XmlIgnore]
            public decimal StBegVBezMKalJahrGesamt
            {
                get
                {
                    if (StBegVBezMKalJahr == null || StBegVBezMKalJahr.Count == 0)
                        return 0m;
                    return StBegVBezMKalJahr.Sum(x => x.Value);
                }
            }
        }
    }
}
