//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34003
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.0.30319.33440.
// 
namespace Dataline.Elster.Lohn.LStB201001 {
    using System.Xml.Serialization;
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.elsterlohn.de/2010-01/XMLSchema", IncludeInSchema=false)]
    public enum ItemsChoiceType{
        
        /// <remarks/>
        Anschriftenzusatz,
        
        /// <remarks/>
        AuslandsPLZ,
        
        /// <remarks/>
        GKPLZ,
        
        /// <remarks/>
        HNrZusatz,
        
        /// <remarks/>
        Hausnummer,
        
        /// <remarks/>
        Ort,
        
        /// <remarks/>
        PLZ,
        
        /// <remarks/>
        Postfach,
        
        /// <remarks/>
        PostfachOrt,
        
        /// <remarks/>
        PostfachPLZ,
        
        /// <remarks/>
        Str,
    }
}