//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34003
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.0.30319.33440.
// 
namespace Dataline.Elster.Lohn.LStB201001 {
    using System.Xml.Serialization;
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(TypeName="lstb_BesteuerungsmerkmaleCType", Namespace="http://www.elsterlohn.de/2010-01/XMLSchema")]
    public partial class lstb_BesteuerungsmerkmaleCType: object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.Generic.List<LStB201001.lstb_BesteuerungsmerkmaleCTypeSteuerklasse> steuerklasseField;
        
        private System.Collections.Generic.List<LStB201001.lstb_BesteuerungsmerkmaleCTypeKinder> kinderField;
        
        private System.Collections.Generic.List<LStB201001.lstb_BesteuerungsmerkmaleCTypeKirchensteuerabzug> kirchensteuerabzugField;
        
        private System.Collections.Generic.List<LStB201001.lstb_SteuerfreibetragCType> steuerfreibetragField;
        
        private System.Collections.Generic.List<LStB201001.lstb_SteuerfreibetragCType> hinzurechnungsbetragField;
        
        /// <remarks/>
        [XmlElement("Steuerklasse")]
        public System.Collections.Generic.List<LStB201001.lstb_BesteuerungsmerkmaleCTypeSteuerklasse> Steuerklasse {
            get {
                return steuerklasseField;
            }
            set {
                steuerklasseField = value;
                RaisePropertyChanged("Steuerklasse");
            }
        }
        
        /// <remarks/>
        [XmlElement("Kinder")]
        public System.Collections.Generic.List<LStB201001.lstb_BesteuerungsmerkmaleCTypeKinder> Kinder {
            get {
                return kinderField;
            }
            set {
                kinderField = value;
                RaisePropertyChanged("Kinder");
            }
        }
        
        /// <remarks/>
        [XmlElement("Kirchensteuerabzug")]
        public System.Collections.Generic.List<LStB201001.lstb_BesteuerungsmerkmaleCTypeKirchensteuerabzug> Kirchensteuerabzug {
            get {
                return kirchensteuerabzugField;
            }
            set {
                kirchensteuerabzugField = value;
                RaisePropertyChanged("Kirchensteuerabzug");
            }
        }
        
        /// <remarks/>
        [XmlElement("Steuerfreibetrag")]
        public System.Collections.Generic.List<LStB201001.lstb_SteuerfreibetragCType> Steuerfreibetrag {
            get {
                return steuerfreibetragField;
            }
            set {
                steuerfreibetragField = value;
                RaisePropertyChanged("Steuerfreibetrag");
            }
        }
        
        /// <remarks/>
        [XmlElement("Hinzurechnungsbetrag")]
        public System.Collections.Generic.List<LStB201001.lstb_SteuerfreibetragCType> Hinzurechnungsbetrag {
            get {
                return hinzurechnungsbetragField;
            }
            set {
                hinzurechnungsbetragField = value;
                RaisePropertyChanged("Hinzurechnungsbetrag");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}