//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34003
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.0.30319.33440.
// 
namespace Dataline.Elster.Lohn.LStB201001 {
    using System.Xml.Serialization;
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="lstb_PersonCType", Namespace="http://www.elsterlohn.de/2010-01/XMLSchema")]
    public partial class lstb_PersonCType: object, System.ComponentModel.INotifyPropertyChanged {
        
        private LStB201001.lstb_PersonCTypeFamilienname familiennameField;
        
        private LStB201001.lstb_PersonCTypeGeburtsname geburtsnameField;
        
        private string geburtsdatumField;
        
        private LStB201001.lstb_AdresseCType adresseField;
        
        private LStB201001.lstb_PersonCTypeGeschlecht geschlechtField;
        
        /// <remarks/>
        public LStB201001.lstb_PersonCTypeFamilienname Familienname {
            get {
                return familiennameField;
            }
            set {
                familiennameField = value;
                RaisePropertyChanged("Familienname");
            }
        }
        
        /// <remarks/>
        public LStB201001.lstb_PersonCTypeGeburtsname Geburtsname {
            get {
                return geburtsnameField;
            }
            set {
                geburtsnameField = value;
                RaisePropertyChanged("Geburtsname");
            }
        }
        
        /// <remarks/>
        public string Geburtsdatum {
            get {
                return geburtsdatumField;
            }
            set {
                geburtsdatumField = value;
                RaisePropertyChanged("Geburtsdatum");
            }
        }
        
        /// <remarks/>
        public LStB201001.lstb_AdresseCType Adresse {
            get {
                return adresseField;
            }
            set {
                adresseField = value;
                RaisePropertyChanged("Adresse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public LStB201001.lstb_PersonCTypeGeschlecht geschlecht {
            get {
                return geschlechtField;
            }
            set {
                geschlechtField = value;
                RaisePropertyChanged("geschlecht");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}