//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34003
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.0.30319.33440.
// 
namespace Dataline.Elster.Lohn.Protocol4 {
    using System.Xml.Serialization;
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="DatenTeilStatusCType", Namespace="http://www.elsterfachmethodik.de/protokollverfahren/version4/XMLSchema")]
    public partial class DatenTeilStatusCType: object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.Generic.List<Protocol4.NutzdatenBlockStatusCType> nutzdatenblockField;
        
        private string transferTicketField;
        
        private Protocol4.DatenTeilStatusCTypeCode codeField;
        
        private string textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Nutzdatenblock")]
        public System.Collections.Generic.List<Protocol4.NutzdatenBlockStatusCType> Nutzdatenblock {
            get {
                return this.nutzdatenblockField;
            }
            set {
                this.nutzdatenblockField = value;
                this.RaisePropertyChanged("Nutzdatenblock");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string transferTicket {
            get {
                return this.transferTicketField;
            }
            set {
                this.transferTicketField = value;
                this.RaisePropertyChanged("transferTicket");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Protocol4.DatenTeilStatusCTypeCode code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("text");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}