//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34003
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.0.30319.33440.
// 
namespace Dataline.Elster.Lohn.Protocol4 {
    using System.Xml.Serialization;
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="NutzdatenBlockStatusCType", Namespace="http://www.elsterfachmethodik.de/protokollverfahren/version4/XMLSchema")]
    public partial class NutzdatenBlockStatusCType: object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.Generic.List<Protocol4.NdSFehlerCType> ndSFehlerField;
        
        private string nutzdatenTicketField;
        
        private Protocol4.NutzdatenBlockStatusCTypeCode codeField;
        
        private string textField;
        
        private string verarbeiteteNdSField;
        
        private string nichtverarbeiteteNdSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NdSFehler")]
        public System.Collections.Generic.List<Protocol4.NdSFehlerCType> NdSFehler {
            get {
                return this.ndSFehlerField;
            }
            set {
                this.ndSFehlerField = value;
                this.RaisePropertyChanged("NdSFehler");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nutzdatenTicket {
            get {
                return this.nutzdatenTicketField;
            }
            set {
                this.nutzdatenTicketField = value;
                this.RaisePropertyChanged("nutzdatenTicket");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Protocol4.NutzdatenBlockStatusCTypeCode code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string verarbeiteteNdS {
            get {
                return this.verarbeiteteNdSField;
            }
            set {
                this.verarbeiteteNdSField = value;
                this.RaisePropertyChanged("verarbeiteteNdS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string nichtverarbeiteteNdS {
            get {
                return this.nichtverarbeiteteNdSField;
            }
            set {
                this.nichtverarbeiteteNdSField = value;
                this.RaisePropertyChanged("nichtverarbeiteteNdS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}