//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// <copyright file="lstb_BesteuerungsmerkmaleCTypeELStAM.cs" company="DATALINE GmbH &amp; Co. KG">
// Copyright (c) DATALINE GmbH &amp; Co. KG. All rights reserved.
// </copyright>

using System.Xml.Serialization;

namespace Dataline.Elster.Lohn
{
    namespace LStB201501
    {
        public partial class lstb_BesteuerungsmerkmaleCTypeELStAM
        {
            public override bool Equals(object obj)
            {
                var other = obj as lstb_BesteuerungsmerkmaleCTypeELStAM;
                if (other == null)
                    return false;

                return this.gueltig_ab == other.gueltig_ab
                    && this.Steuerfreibetrag == other.Steuerfreibetrag
                    && this.Hinzurechnungsbetrag == other.Hinzurechnungsbetrag
                    && this.Kinder == other.Kinder
                    && this.Kirchensteuerabzug == other.Kirchensteuerabzug
                    && this.Steuerklasse == other.Steuerklasse;
            }

            public override int GetHashCode()
            {
                var result = gueltig_ab.GetHashCode();
                if (Hinzurechnungsbetrag != null)
                    result ^= Hinzurechnungsbetrag.GetHashCode();
                if (Steuerfreibetrag != null)
                    result ^= Steuerfreibetrag.GetHashCode();
                if (Kinder != null)
                    result ^= Kinder.GetHashCode();
                if (Kirchensteuerabzug != null)
                    result ^= Kirchensteuerabzug.GetHashCode();
                if (Steuerklasse != null)
                    result ^= Steuerklasse.GetHashCode();
                return result;
            }
        }
    }
}
