//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34003
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.0.30319.33440.
// 
namespace Dataline.Elster.Anmeldung.UStA200501 {
    using System.Xml.Serialization;
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThrough()]
    [XmlType(Namespace="http://www.elster.de/2002/XMLSchema")]
    public partial class usta_UmsatzsteuervoranmeldungCType: object, System.ComponentModel.INotifyPropertyChanged {
        
        private usta_JahrSType jahrField;
        
        private usta_ZeitraumSType zeitraumField;
        
        private string steuernummerField;
        
        private string kz09Field;
        
        private usta_Kz10SType kz10Field;
        
        private bool kz10FieldSpecified;
        
        private usta_Kz26SType kz26Field;
        
        private bool kz26FieldSpecified;
        
        private usta_Kz29SType kz29Field;
        
        private bool kz29FieldSpecified;
        
        private string kz35Field;
        
        private string kz36Field;
        
        private string kz39Field;
        
        private string kz41Field;
        
        private string kz42Field;
        
        private string kz43Field;
        
        private string kz44Field;
        
        private string kz45Field;
        
        private string kz48Field;
        
        private string kz49Field;
        
        private string kz51Field;
        
        private string kz52Field;
        
        private string kz53Field;
        
        private string kz59Field;
        
        private string kz60Field;
        
        private string kz61Field;
        
        private string kz62Field;
        
        private string kz63Field;
        
        private string kz64Field;
        
        private string kz65Field;
        
        private string kz66Field;
        
        private string kz67Field;
        
        private string kz69Field;
        
        private string kz73Field;
        
        private string kz74Field;
        
        private string kz76Field;
        
        private string kz77Field;
        
        private string kz80Field;
        
        private string kz83Field;
        
        private string kz84Field;
        
        private string kz85Field;
        
        private string kz86Field;
        
        private string kz91Field;
        
        private string kz93Field;
        
        private string kz94Field;
        
        private string kz95Field;
        
        private string kz96Field;
        
        private string kz97Field;
        
        private string kz98Field;
        
        /// <remarks/>
        public usta_JahrSType Jahr {
            get {
                return jahrField;
            }
            set {
                jahrField = value;
                RaisePropertyChanged("Jahr");
            }
        }
        
        /// <remarks/>
        public usta_ZeitraumSType Zeitraum {
            get {
                return zeitraumField;
            }
            set {
                zeitraumField = value;
                RaisePropertyChanged("Zeitraum");
            }
        }
        
        /// <remarks/>
        public string Steuernummer {
            get {
                return steuernummerField;
            }
            set {
                steuernummerField = value;
                RaisePropertyChanged("Steuernummer");
            }
        }
        
        /// <remarks/>
        public string Kz09 {
            get {
                return kz09Field;
            }
            set {
                kz09Field = value;
                RaisePropertyChanged("Kz09");
            }
        }
        
        /// <remarks/>
        public usta_Kz10SType Kz10 {
            get {
                return kz10Field;
            }
            set {
                kz10Field = value;
                RaisePropertyChanged("Kz10");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Kz10Specified {
            get {
                return kz10FieldSpecified;
            }
            set {
                kz10FieldSpecified = value;
                RaisePropertyChanged("Kz10Specified");
            }
        }
        
        /// <remarks/>
        public usta_Kz26SType Kz26 {
            get {
                return kz26Field;
            }
            set {
                kz26Field = value;
                RaisePropertyChanged("Kz26");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Kz26Specified {
            get {
                return kz26FieldSpecified;
            }
            set {
                kz26FieldSpecified = value;
                RaisePropertyChanged("Kz26Specified");
            }
        }
        
        /// <remarks/>
        public usta_Kz29SType Kz29 {
            get {
                return kz29Field;
            }
            set {
                kz29Field = value;
                RaisePropertyChanged("Kz29");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Kz29Specified {
            get {
                return kz29FieldSpecified;
            }
            set {
                kz29FieldSpecified = value;
                RaisePropertyChanged("Kz29Specified");
            }
        }
        
        /// <remarks/>
        public string Kz35 {
            get {
                return kz35Field;
            }
            set {
                kz35Field = value;
                RaisePropertyChanged("Kz35");
            }
        }
        
        /// <remarks/>
        public string Kz36 {
            get {
                return kz36Field;
            }
            set {
                kz36Field = value;
                RaisePropertyChanged("Kz36");
            }
        }
        
        /// <remarks/>
        public string Kz39 {
            get {
                return kz39Field;
            }
            set {
                kz39Field = value;
                RaisePropertyChanged("Kz39");
            }
        }
        
        /// <remarks/>
        public string Kz41 {
            get {
                return kz41Field;
            }
            set {
                kz41Field = value;
                RaisePropertyChanged("Kz41");
            }
        }
        
        /// <remarks/>
        public string Kz42 {
            get {
                return kz42Field;
            }
            set {
                kz42Field = value;
                RaisePropertyChanged("Kz42");
            }
        }
        
        /// <remarks/>
        public string Kz43 {
            get {
                return kz43Field;
            }
            set {
                kz43Field = value;
                RaisePropertyChanged("Kz43");
            }
        }
        
        /// <remarks/>
        public string Kz44 {
            get {
                return kz44Field;
            }
            set {
                kz44Field = value;
                RaisePropertyChanged("Kz44");
            }
        }
        
        /// <remarks/>
        public string Kz45 {
            get {
                return kz45Field;
            }
            set {
                kz45Field = value;
                RaisePropertyChanged("Kz45");
            }
        }
        
        /// <remarks/>
        public string Kz48 {
            get {
                return kz48Field;
            }
            set {
                kz48Field = value;
                RaisePropertyChanged("Kz48");
            }
        }
        
        /// <remarks/>
        public string Kz49 {
            get {
                return kz49Field;
            }
            set {
                kz49Field = value;
                RaisePropertyChanged("Kz49");
            }
        }
        
        /// <remarks/>
        public string Kz51 {
            get {
                return kz51Field;
            }
            set {
                kz51Field = value;
                RaisePropertyChanged("Kz51");
            }
        }
        
        /// <remarks/>
        public string Kz52 {
            get {
                return kz52Field;
            }
            set {
                kz52Field = value;
                RaisePropertyChanged("Kz52");
            }
        }
        
        /// <remarks/>
        public string Kz53 {
            get {
                return kz53Field;
            }
            set {
                kz53Field = value;
                RaisePropertyChanged("Kz53");
            }
        }
        
        /// <remarks/>
        public string Kz59 {
            get {
                return kz59Field;
            }
            set {
                kz59Field = value;
                RaisePropertyChanged("Kz59");
            }
        }
        
        /// <remarks/>
        public string Kz60 {
            get {
                return kz60Field;
            }
            set {
                kz60Field = value;
                RaisePropertyChanged("Kz60");
            }
        }
        
        /// <remarks/>
        public string Kz61 {
            get {
                return kz61Field;
            }
            set {
                kz61Field = value;
                RaisePropertyChanged("Kz61");
            }
        }
        
        /// <remarks/>
        public string Kz62 {
            get {
                return kz62Field;
            }
            set {
                kz62Field = value;
                RaisePropertyChanged("Kz62");
            }
        }
        
        /// <remarks/>
        public string Kz63 {
            get {
                return kz63Field;
            }
            set {
                kz63Field = value;
                RaisePropertyChanged("Kz63");
            }
        }
        
        /// <remarks/>
        public string Kz64 {
            get {
                return kz64Field;
            }
            set {
                kz64Field = value;
                RaisePropertyChanged("Kz64");
            }
        }
        
        /// <remarks/>
        public string Kz65 {
            get {
                return kz65Field;
            }
            set {
                kz65Field = value;
                RaisePropertyChanged("Kz65");
            }
        }
        
        /// <remarks/>
        public string Kz66 {
            get {
                return kz66Field;
            }
            set {
                kz66Field = value;
                RaisePropertyChanged("Kz66");
            }
        }
        
        /// <remarks/>
        public string Kz67 {
            get {
                return kz67Field;
            }
            set {
                kz67Field = value;
                RaisePropertyChanged("Kz67");
            }
        }
        
        /// <remarks/>
        public string Kz69 {
            get {
                return kz69Field;
            }
            set {
                kz69Field = value;
                RaisePropertyChanged("Kz69");
            }
        }
        
        /// <remarks/>
        public string Kz73 {
            get {
                return kz73Field;
            }
            set {
                kz73Field = value;
                RaisePropertyChanged("Kz73");
            }
        }
        
        /// <remarks/>
        public string Kz74 {
            get {
                return kz74Field;
            }
            set {
                kz74Field = value;
                RaisePropertyChanged("Kz74");
            }
        }
        
        /// <remarks/>
        public string Kz76 {
            get {
                return kz76Field;
            }
            set {
                kz76Field = value;
                RaisePropertyChanged("Kz76");
            }
        }
        
        /// <remarks/>
        public string Kz77 {
            get {
                return kz77Field;
            }
            set {
                kz77Field = value;
                RaisePropertyChanged("Kz77");
            }
        }
        
        /// <remarks/>
        public string Kz80 {
            get {
                return kz80Field;
            }
            set {
                kz80Field = value;
                RaisePropertyChanged("Kz80");
            }
        }
        
        /// <remarks/>
        public string Kz83 {
            get {
                return kz83Field;
            }
            set {
                kz83Field = value;
                RaisePropertyChanged("Kz83");
            }
        }
        
        /// <remarks/>
        public string Kz84 {
            get {
                return kz84Field;
            }
            set {
                kz84Field = value;
                RaisePropertyChanged("Kz84");
            }
        }
        
        /// <remarks/>
        public string Kz85 {
            get {
                return kz85Field;
            }
            set {
                kz85Field = value;
                RaisePropertyChanged("Kz85");
            }
        }
        
        /// <remarks/>
        public string Kz86 {
            get {
                return kz86Field;
            }
            set {
                kz86Field = value;
                RaisePropertyChanged("Kz86");
            }
        }
        
        /// <remarks/>
        public string Kz91 {
            get {
                return kz91Field;
            }
            set {
                kz91Field = value;
                RaisePropertyChanged("Kz91");
            }
        }
        
        /// <remarks/>
        public string Kz93 {
            get {
                return kz93Field;
            }
            set {
                kz93Field = value;
                RaisePropertyChanged("Kz93");
            }
        }
        
        /// <remarks/>
        public string Kz94 {
            get {
                return kz94Field;
            }
            set {
                kz94Field = value;
                RaisePropertyChanged("Kz94");
            }
        }
        
        /// <remarks/>
        public string Kz95 {
            get {
                return kz95Field;
            }
            set {
                kz95Field = value;
                RaisePropertyChanged("Kz95");
            }
        }
        
        /// <remarks/>
        public string Kz96 {
            get {
                return kz96Field;
            }
            set {
                kz96Field = value;
                RaisePropertyChanged("Kz96");
            }
        }
        
        /// <remarks/>
        public string Kz97 {
            get {
                return kz97Field;
            }
            set {
                kz97Field = value;
                RaisePropertyChanged("Kz97");
            }
        }
        
        /// <remarks/>
        public string Kz98 {
            get {
                return kz98Field;
            }
            set {
                kz98Field = value;
                RaisePropertyChanged("Kz98");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}