//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// <copyright file="lstb_BesteuerungsmerkmaleCTypeELStAM.cs" company="DATALINE GmbH &amp; Co. KG">
// Copyright (c) DATALINE GmbH &amp; Co. KG. All rights reserved.
// </copyright>

using System.Xml.Serialization;

namespace Dataline.Elster.Lohn
{
    namespace LStB201301
    {
        public partial class lstb_BesteuerungsmerkmaleCTypeELStAM
        {
            [XmlIgnore]
            private lstb_BesteuerungsmerkmaleCTypeELStAMHinzurechnungsbetrag _hinzurechnungsbetrag;

            [XmlIgnore]
            public lstb_BesteuerungsmerkmaleCTypeELStAMHinzurechnungsbetrag Hinzurechnungsbetrag
            {
                get
                {
                    if (_hinzurechnungsbetrag == null)
                        _hinzurechnungsbetrag = Item as lstb_BesteuerungsmerkmaleCTypeELStAMHinzurechnungsbetrag;
                    return _hinzurechnungsbetrag;
                }
                set
                {
                    _hinzurechnungsbetrag = value;
                }
            }

            [XmlIgnore]
            private lstb_BesteuerungsmerkmaleCTypeELStAMSteuerfreibetrag _steuerfreibetrag;

            [XmlIgnore]
            public lstb_BesteuerungsmerkmaleCTypeELStAMSteuerfreibetrag Steuerfreibetrag
            {
                get
                {
                    if (_steuerfreibetrag == null)
                        _steuerfreibetrag = Item as lstb_BesteuerungsmerkmaleCTypeELStAMSteuerfreibetrag;
                    return _steuerfreibetrag;
                }
                set
                {
                    _steuerfreibetrag = value;
                }
            }

            public override bool Equals(object obj)
            {
                var other = obj as lstb_BesteuerungsmerkmaleCTypeELStAM;
                if (other == null)
                    return false;

                return this.gueltig_ab == other.gueltig_ab && this.Item == other.Item && this.Kinder == other.Kinder && this.Kirchensteuerabzug == other.Kirchensteuerabzug && this.Steuerklasse == other.Steuerklasse;
            }

            public override int GetHashCode()
            {
                var result = gueltig_ab.GetHashCode();
                if (Item != null)
                    result ^= Item.GetHashCode();
                if (Kinder != null)
                    result ^= Kinder.GetHashCode();
                if (Kirchensteuerabzug != null)
                    result ^= Kirchensteuerabzug.GetHashCode();
                if (Steuerklasse != null)
                    result ^= Steuerklasse.GetHashCode();
                return result;
            }
        }
    }
}
