//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34003
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.0.30319.33440.
// 
namespace Dataline.Elster.Lohn.LStB201301 {
    using System.Xml.Serialization;
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.elsterlohn.de/2013-01/XMLSchema")]
    public partial class lstb_PersonCTypeFamilienname: object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string vornameField;
        
        private string namensvorsatzField;
        
        private string namenszusatzField;
        
        private string titelField;
        
        /// <remarks/>
        public string Name {
            get {
                return nameField;
            }
            set {
                nameField = value;
                RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        public string Vorname {
            get {
                return vornameField;
            }
            set {
                vornameField = value;
                RaisePropertyChanged("Vorname");
            }
        }
        
        /// <remarks/>
        public string Namensvorsatz {
            get {
                return namensvorsatzField;
            }
            set {
                namensvorsatzField = value;
                RaisePropertyChanged("Namensvorsatz");
            }
        }
        
        /// <remarks/>
        public string Namenszusatz {
            get {
                return namenszusatzField;
            }
            set {
                namenszusatzField = value;
                RaisePropertyChanged("Namenszusatz");
            }
        }
        
        /// <remarks/>
        public string Titel {
            get {
                return titelField;
            }
            set {
                titelField = value;
                RaisePropertyChanged("Titel");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}