//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34003
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.0.30319.33440.
// 
namespace Dataline.Elster.Lohn.Protocol3 {
    using System.Xml.Serialization;
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(TypeName="ProtokollAnforderungCType", Namespace="http://www.elsterfachmethodik.de/protokollverfahren/version3/XMLSchema")]
    [XmlRoot("ProtokollAnforderung", Namespace="http://www.elsterfachmethodik.de/protokollverfahren/version3/XMLSchema", IsNullable=false)]
    public partial class ProtokollAnforderungCType: object, System.ComponentModel.INotifyPropertyChanged {
        
        private string transferTicketField;
        
        private Protocol3.ProtokollAnforderungVersionSType versionField;
        
        private Protocol3.ProtokollVersionSType protokollVersionField;
        
        /// <remarks/>
        public string TransferTicket {
            get {
                return transferTicketField;
            }
            set {
                transferTicketField = value;
                RaisePropertyChanged("TransferTicket");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Protocol3.ProtokollAnforderungVersionSType version {
            get {
                return versionField;
            }
            set {
                versionField = value;
                RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Protocol3.ProtokollVersionSType protokollVersion {
            get {
                return protokollVersionField;
            }
            set {
                protokollVersionField = value;
                RaisePropertyChanged("protokollVersion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}