//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34003
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.0.30319.33440.
// 
namespace Dataline.Elster.Anmeldung.UStA201102 {
    using System.Xml.Serialization;
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
    [XmlType(Namespace="http://www.elster.de/2002/XMLSchema")]
    public enum usta_ZeitraumSType{
        
        /// <remarks/>
        [XmlEnum("07")]
        Item07,
        
        /// <remarks/>
        [XmlEnum("08")]
        Item08,
        
        /// <remarks/>
        [XmlEnum("09")]
        Item09,
        
        /// <remarks/>
        [XmlEnum("10")]
        Item10,
        
        /// <remarks/>
        [XmlEnum("11")]
        Item11,
        
        /// <remarks/>
        [XmlEnum("12")]
        Item12,
        
        /// <remarks/>
        [XmlEnum("43")]
        Item43,
        
        /// <remarks/>
        [XmlEnum("44")]
        Item44,
    }
}